/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as odpCounterfeitConcernSol from './ODPCounterfeitConcern.sol/index.js';
export type { odpCounterfeitConcernSol };
import type * as odpWalletDocumentAnchorSol from './ODPWalletDocumentAnchor.sol/index.js';
export type { odpWalletDocumentAnchorSol };
import type * as objectDigitalPassportSol from './ObjectDigitalPassport.sol/index.js';
export type { objectDigitalPassportSol };
import type * as examples from './examples/index.js';
export type { examples };
export type { ODPPassportLib } from './ODPPassportLib.js';
export * as factories from './factories/index.js';
export type { IODPRegistryForCounterfeit } from './ODPCounterfeitConcern.sol/IODPRegistryForCounterfeit.js';
export { IODPRegistryForCounterfeit__factory } from './factories/ODPCounterfeitConcern.sol/IODPRegistryForCounterfeit__factory.js';
export type { ODPCounterfeitConcern } from './ODPCounterfeitConcern.sol/ODPCounterfeitConcern.js';
export { ODPCounterfeitConcern__factory } from './factories/ODPCounterfeitConcern.sol/ODPCounterfeitConcern__factory.js';
export { ODPPassportLib__factory } from './factories/ODPPassportLib__factory.js';
export type { IODPWalletLookup } from './ODPWalletDocumentAnchor.sol/IODPWalletLookup.js';
export { IODPWalletLookup__factory } from './factories/ODPWalletDocumentAnchor.sol/IODPWalletLookup__factory.js';
export type { ODPWalletDocumentAnchor } from './ODPWalletDocumentAnchor.sol/ODPWalletDocumentAnchor.js';
export { ODPWalletDocumentAnchor__factory } from './factories/ODPWalletDocumentAnchor.sol/ODPWalletDocumentAnchor__factory.js';
export type { IODPExtension } from './ObjectDigitalPassport.sol/IODPExtension.js';
export { IODPExtension__factory } from './factories/ObjectDigitalPassport.sol/IODPExtension__factory.js';
export type { ObjectDigitalPassport } from './ObjectDigitalPassport.sol/ObjectDigitalPassport.js';
export { ObjectDigitalPassport__factory } from './factories/ObjectDigitalPassport.sol/ObjectDigitalPassport__factory.js';
export type { ODPPassThroughDigitalExtension } from './examples/ODPPassThroughDigitalExtension.js';
export { ODPPassThroughDigitalExtension__factory } from './factories/examples/ODPPassThroughDigitalExtension__factory.js';
export type { ODPPassThroughPhysicalExtension } from './examples/ODPPassThroughPhysicalExtension.js';
export { ODPPassThroughPhysicalExtension__factory } from './factories/examples/ODPPassThroughPhysicalExtension__factory.js';