/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IODPRegistryForExtensionMint } from './IODPRegistryForExtensionMint.js';
export type { ODPExtensionMintRouter } from './ODPExtensionMintRouter.js';