// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./ODPErrors.sol";
import {
    DigitalMintInputs,
    MixedMintInputs,
    PassportCoreMintInputs,
    PhysicalMintInputs
} from "./ODPPassportTypes.sol";
import "./ODPPassportLib.sol";

/**
 * Object Digital Passport — Smart Contract
 * @author Andrei Chernikov
 * Specification v0.5 (reference branch)
 * License: MIT
 *
 * Deployed on: Polygon PoS (chain ID 137)
 * Testnet:     Polygon Amoy (chain ID 80002)
 *
 * Three registries in one contract:
 *   1. Creator Registry  — C / B / P / M identifiers
 *   2. Passport Registry — physical and digital object records
 *   3. Proof Registry    — institution attestations (optional satellite in size-constrained deployments)
 *
 * All IDs are randomly generated by the contract.
 * A registered profile ID (`creatorId`) is mandatory for minting and proof submission.
 *
 * IMMUTABILITY:
 *   This contract is not upgradeable by design.
 *   No owner. No admin. No pause function. No selfdestruct.
 *   Rules cannot change after deployment.
 *   Protocol updates require a new contract (v0.2, v0.3, etc.).
 *
 * VERSIONING (normative detail: SPEC.md):
 *   Reference lines v0.1, v0.2, and v0.3 are separate registries — not backward compatible
 *   (different address, bytecode, ABI). Integrators must not treat them as drop-in replacements.
 *   The v0.3 line is documented in SPEC as aligned toward a future stable v1 (migration to be
 *   defined in v1); this is design intent, not an in-place upgrade guarantee.
 *   v0.5 reference: classification fields (`title`, `domain`, `objectType`, `contentClass`,
 *   lifecycle / AI / verification / edition), `mixed` objects, mutable current-state fields
 *   (`status`, location, rights, condition / damage history), and an optional NDPP/offline-public
 *   commitment pointer promoted on-chain.
 *   NFC / NDPP is an optional carrier layer only: it does not replace Passport ID, `dataHash`,
 *   canonical `.odpass`, or the main on-chain registry model.
 *   Type-definition governance is off-chain / SPEC where noted (saves bytecode).
 *
 * SECURITY NOTES:
 *   - v0.2+: no protocol fee — native token only pays network gas (no POL routed to fee burn)
 *   - Extension mint uses staticcalls to registered `IODPExtension` (view) then state writes — no reentrancy loop into core
 *   - Solidity 0.8.20 — overflow/underflow protection built in
 *   - Access control enforced via `if (!(…)) revert EC(n);` on write paths
 *   - On-chain randomness (block.prevrandao + gasleft) is not
 *     cryptographically secure but is acceptable here since IDs
 *     carry no financial value — only human-readability
 *   - NFC: NTAG424DNA or NTAG424DNA_TAGTAMPER — issuer declares model; verify is off-chain per SPEC
 *   - Proof institutions (P) and museums (M) are open registration — verifiers must warn
 *     users to confirm P/M-type IDs on official institution websites
 *   - Mint agent (v0.3): optional two-step handshake — agent `requestMintAgentRole(principalCreatorId)`,
 *     principal `confirmMintAgentRole(agent)` — then agent may mint with `mintOnBehalfOfCreatorId`;
 *     `Passport.creator` / `owner` are the principal wallet; `Passport.mintAgent` records who sent the tx (0 = self)
 *   - Creator is trusted to physically install the correct chip model
 *     The contract cannot verify hardware — only the declared model
 *   - Anti-spam: monthly mint-rate limit (no protocol fee — gas only)
 *   - Rate limit (per wallet, per calendar month): C = 1000, B = 100_000, P/M = unlimited
 *   - Passport namespace: 100M IDs per year+month (previously 10M)
 *   - P-type whitelist is intentionally off-chain — see external repos
 *
 * SOURCE CODE:
 *   Published at: https://github.com/object-digital-passport/object-digital-passport
 *   Anyone can read, verify, fork, or deploy their own instance.
 *
 * DEPLOY (EIP-170):
 *   Deploy linked library `ODPPassportLib` first, then deploy this contract with compiler linker
 *   metadata pointing at that library address (see `deploy/scripts/deploy.js`).
 */
interface IODPRelationsLookup {
    function mintAgentForCreator(string calldata creatorId) external view returns (address);
    function getCreatorPublishingDelegation(address creatorWallet) external view returns (address agent, uint256 expiresAt);
}

contract ObjectDigitalPassport {

    // ─── Constants ────────────────────────────────────────────────────────────

    bytes1 constant TYPE_C = "C";
    bytes1 constant TYPE_B = "B";
    bytes1 constant TYPE_P = "P";
    bytes1 constant TYPE_M = "M";

    string constant OBJECT_PHYSICAL = "physical";
    string constant OBJECT_DIGITAL  = "digital";
    string constant OBJECT_MIXED    = "mixed";

    // On-chain spec line (variant: two uint8s, human-readable as major.minor).
    // Not `public` — each public constant adds a getter (~bytecode budget, EIP-170). Use `CONTRACT_VERSION` / 16 and % 16.
    uint8 internal constant SPEC_MAJOR = 0;
    uint8 internal constant SPEC_MINOR = 5;

    /// Packed byte in `Passport.contractVersion`: `SPEC_MAJOR * 16 + SPEC_MINOR` (each < 16).
    /// **v0.5** uses packed byte **5**. ABI name for the passport identifier is `passportId`.
    uint8 public constant CONTRACT_VERSION = SPEC_MAJOR * 16 + SPEC_MINOR;

    // Anti-spam: per-wallet, per-calendar-month mint caps (no protocol fee). Tier follows profile ID prefix (C/B/P/M).
    uint32 internal constant MONTHLY_LIMIT_C = 1000;
    uint32 internal constant MONTHLY_LIMIT_B = 100_000;

    // ─── Structs ──────────────────────────────────────────────────────────────

    struct CreatorRecord {
        string  creatorId;    // "C-482-930-174-005"
        address wallet;
        bytes1  typePrefix;   // "C", "B", "P", or "M" — stored as bytes1 for gas efficiency
        uint256 timestamp;
    }

    struct Passport {
        string  passportId;       // Passport ID (SPEC); ODP-… string; ABI name passportId
        uint8   contractVersion; // packed SPEC_MAJOR/SPEC_MINOR (see CONTRACT_VERSION) at mint
        address creator;       // immutable issuer wallet at mint
        address owner;         // current holder; starts as creator; changes via transferPassport
        string  creatorId;     // Profile ID (SPEC); mandatory
        uint32  year;          // uint32 supports any year from 1 to 4,294,967,295
        uint8   month;
        string  title;         // human-readable title for basic on-chain verification
        string  domain;        // area / field (e.g. contemporary_art, software)
        string  objectType;    // "physical", "digital", or "mixed"
        uint8   contentClass;  // 1..6 taxonomy: static/time_based/spatial/textual/composite/executable
        uint8   lifecycleStatus;
        uint8   aiStatus;
        uint8   verificationMethod;
        uint8   editionModel;
        string  currentLocation;
        string  rightsNote;
        string  conditionNote;
        bytes32 damageHistoryHash;
        string  damageHistoryUrl;
        /// Commitment to canonical `passport.json` (SPEC §10). New JSON keys need no on-chain schema:
        /// evolve **SPEC** + canonicalization for **new** mints only; `dataHash` is **immutable** after mint, so
        /// the hashed byte string for an existing passport cannot gain new integrity-bound fields without breaking verify.
        /// Optional UI-only or manifest-only fields live off this anchor. Future lines may add auxiliary commitments if needed.
        bytes32 dataHash;      // SHA-256 of minified passport.json
        bytes32 imageHash;     // SHA-256 of primary image. bytes32(0) = none
        bytes32 imageHash2;    // optional 2nd image (max 3 on-chain hashes total)
        bytes32 imageHash3;    // optional 3rd image
        bytes32 fileHash;      // SHA-256 of digital file. bytes32(0) if physical-only
        uint8   sealType;      // 1=NFC, 2=numbered, 3=both. 0 if digital-only
        bytes32 sealHash;      // SHA-256 of seal object. bytes32(0) if digital-only
        bytes   nfcPublicKey;  // NFC chip public key. empty if no NFC seal
        string  nfcModel;      // "NTAG424DNA" or "NTAG424DNA_TAGTAMPER" if NFC. empty if no NFC seal
        string  dataUrl;
        string  imageUrl;
        string  imageUrl2;     // optional URL hints for extra images
        string  imageUrl3;
        uint256 timestamp;
        bool    revoked;       // passport revoked (creator or governance)
        uint256 revokedAt;
        bytes32 revocationReasonHash; // keccak256 of UTF-8 reason; 0 if not revoked
        /// Optional second commitment (e.g. PDF COA); independent of `dataHash`. Mutable by creator or governance.
        bytes32 auxCommitmentHash;
        string  auxCommitmentUri; // optional HTTPS hint; max 512 when hash non-zero; both zero when unused
        /// Optional NDPP / offline-public commitment for a carrier-layer payload
        /// (e.g. NFC-compatible NDEF, QR-delivered bytes, or public snapshot). Independent of `dataHash`.
        bytes32 ndppCommitmentHash;
        string  ndppCommitmentUri; // optional HTTPS hint; max 512 when hash non-zero; both zero when unused
        /// Wallet that executed the mint for `creator`’s profile; `address(0)` = principal minted themselves.
        address mintAgent;
    }

    struct ProofRecord {
        string  proofId;         // "PRF-2031-03-7392018"
        uint8   contractVersion; // packed SPEC_MAJOR/SPEC_MINOR at submission
        string  prover;          // Profile ID of P- or M-type institution / attestor
        string  passportId;         // attested passport
        bytes32 noteHash;        // SHA-256 of attached document. bytes32(0) = none
        string  noteUrl;
        uint256 timestamp;
    }

    struct PassportHeaderView {
        string  passportId;
        uint8   contractVersion;
        address creator;
        address owner;
        string  creatorId;
        uint32  year;
        uint8   month;
        string  title;
        string  domain;
        string  objectType;
    }

    struct PassportClassificationView {
        uint8   contentClass;
        uint8   lifecycleStatus;
        uint8   aiStatus;
        uint8   verificationMethod;
        uint8   editionModel;
        uint256 timestamp;
        bool    revoked;
        uint256 revokedAt;
        bytes32 revocationReasonHash;
        address mintAgent;
    }

    struct PassportMediaView {
        bytes32 dataHash;
        string  dataUrl;
        bytes32 imageHash;
        string  imageUrl;
        bytes32 imageHash2;
        string  imageUrl2;
        bytes32 imageHash3;
        string  imageUrl3;
        bytes32 fileHash;
    }

    struct PassportPhysicalView {
        uint8   sealType;
        bytes32 sealHash;
        bytes   nfcPublicKey;
        string  nfcModel;
    }

    struct PassportStateView {
        string  currentLocation;
        string  rightsNote;
        string  conditionNote;
        bytes32 damageHistoryHash;
        string  damageHistoryUrl;
        bytes32 auxCommitmentHash;
        string  auxCommitmentUri;
        bytes32 ndppCommitmentHash;
        string  ndppCommitmentUri;
    }

    // ─── Storage ──────────────────────────────────────────────────────────────

    // Creator Registry
    mapping(string  => CreatorRecord) private _creators;
    mapping(address => string)        private _walletToCreatorId;
    mapping(uint64  => bool)          private _creatorNumberTaken;
    uint256 private _creatorNonce;

    // Passport Registry
    // key = year * 100 + month → set of random numbers taken
    mapping(uint32 => mapping(uint32 => bool)) private _passportNumberTaken;
    mapping(string => Passport)   private _passports;
    mapping(address => string[])  private _creatorPassports;
    uint256 private _passportNonce;

    // Rate limiting — mints per wallet per calendar month (C/B tiers; P skips limit)
    // key = address → (yearMonth uint32 e.g. 202603) → count
    mapping(address => mapping(uint32 => uint32)) private _mintCount;

    /// Governance address (multisig / DAO): may revoke passports alongside creator.
    /// Type-definition governance is documented in SPEC; on-chain timelock registry was omitted for bytecode size.
    address public governance;

    /// Optional satellite for P-affiliation, mint-agent delegation, and creator publishing delegation.
    address private relationsSatellite;
    /// Optional trusted router for extension mints; when calling through it, `_resolveMintPrincipal` uses `tx.origin`.
    address private extensionRouter;

    // ─── Events ───────────────────────────────────────────────────────────────

    event CreatorRegistered(
        string  indexed creatorId,
        address indexed wallet,
        bytes1          typePrefix,
        uint256         timestamp
    );

    event PassportMinted(
        string  indexed passportId,
        address indexed creator,
        string          creatorId,
        string          title,
        string          domain,
        string          objectType,
        uint8           contentClass,
        uint32          year,
        uint8           month,
        bytes32         dataHash,
        uint8           sealType,   // 0=digital, 1=NFC, 2=numbered, 3=both
        string          nfcModel,   // "NTAG424DNA" / "NTAG424DNA_TAGTAMPER" or "" if no NFC
        uint256         timestamp,
        address         mintAgent    // address(0) if principal called mint; else delegate wallet
    );

    event PassportUrlsUpdated(
        string indexed passportId,
        string         newDataUrl,
        string         newImageUrl
    );

    event PassportTransferred(
        string  indexed passportId,
        address indexed from,
        address indexed to,
        uint256 timestamp
    );

    event PassportRevoked(
        string  indexed passportId,
        address indexed revokedBy,
        bytes32 reasonHash,
        uint256 timestamp
    );

    event PassportAuxCommitmentUpdated(
        string  passportId,
        bytes32 newHash,
        string  newUri,
        address updatedBy,
        uint256 timestamp
    );

    event PassportNdppCommitmentUpdated(
        string  passportId,
        bytes32 newHash,
        string  newUri,
        address updatedBy,
        uint256 timestamp
    );

    event PassportStatusUpdated(
        string indexed passportId,
        uint8 newLifecycleStatus,
        address updatedBy,
        uint256 timestamp
    );

    event PassportLocationUpdated(
        string indexed passportId,
        string newLocation,
        address updatedBy,
        uint256 timestamp
    );

    event PassportRightsUpdated(
        string indexed passportId,
        string newRightsNote,
        address updatedBy,
        uint256 timestamp
    );

    event PassportConditionUpdated(
        string indexed passportId,
        string newConditionNote,
        bytes32 newDamageHistoryHash,
        string newDamageHistoryUrl,
        address updatedBy,
        uint256 timestamp
    );

    // ─── Constructor ──────────────────────────────────────────────────────────

    constructor() {
        governance = msg.sender;
    }

    /// Governance may be a multisig or DAO-controlled address off-chain.
    function transferGovernance(address newGovernance) external {
        if (!(msg.sender == governance)) revert EC(56);
        if (!(newGovernance != address(0))) revert EC(55);
        governance = newGovernance;
    }

    /// @notice Register or clear the optional relations satellite used for affiliation and delegation flows.
    function setRelationsSatellite(address satellite) external {
        if (!(msg.sender == governance)) revert EC(56);
        relationsSatellite = satellite;
    }

    /// @notice Register or clear the optional extension mint router.
    function setExtensionRouter(address router) external {
        if (!(msg.sender == governance)) revert EC(56);
        extensionRouter = router;
    }

    // ─── Creator Registry ─────────────────────────────────────────────────────

    /**
     * Register as a Creator (C), Brand (B), Proof Institution (P), or Museum (M).
     * One registration per wallet. Permanent.
     * Type prefix must be "C", "B", "P", or "M" — enforced by contract.
     * The 12-digit number is randomly generated — cannot be chosen.
     *
     * Cost: network gas only (no protocol fee).
     */
    function registerCreator(bytes1 typePrefix)
        external
        returns (string memory creatorId)
    {
        if (!(_isValidType(typePrefix))) revert EC(54);
        if (!(bytes(_walletToCreatorId[msg.sender]).length == 0)) revert EC(53);

        uint64 number = _generateCreatorNumber();
        creatorId     = ODPPassportLib.buildCreatorId(typePrefix, number);

        _creators[creatorId] = CreatorRecord({
            creatorId:  creatorId,
            wallet:     msg.sender,
            typePrefix: typePrefix,
            timestamp:  block.timestamp
        });

        _walletToCreatorId[msg.sender] = creatorId;
        _creatorNumberTaken[number]    = true;

        emit CreatorRegistered(creatorId, msg.sender, typePrefix, block.timestamp);
        return creatorId;
    }

    function getCreator(string calldata creatorId)
        external view returns (CreatorRecord memory)
    {
        if (!(bytes(_creators[creatorId].creatorId).length > 0)) revert EC(2);
        return _creators[creatorId];
    }

    function getCreatorByWallet(address wallet)
        external view returns (string memory)
    {
        return _walletToCreatorId[wallet];
    }

    function _stringArraySlice(string[] storage arr, uint256 offset, uint256 limit)
        internal
        view
        returns (string[] memory result, uint256 total)
    {
        total = arr.length;
        if (offset >= total) {
            return (new string[](0), total);
        }
        uint256 end = offset + limit;
        if (end > total) {
            end = total;
        }
        uint256 n = end - offset;
        result = new string[](n);
        for (uint256 i = 0; i < n; i++) {
            result[i] = arr[offset + i];
        }
    }

    // ─── Passport Registry — Mint ─────────────────────────────────────────────

    function _mintDigitalCommit(
        string memory creatorId,
        DigitalMintInputs memory m,
        bool dataUrlIsFolderBase,
        address principalWallet,
        address mintAgentForPassport
    ) internal returns (string memory passportId) {
        passportId = _generatePassportId(m.core.year, m.core.month);
        string memory resolvedDataUrl = ODPPassportLib.resolveMintDataUrlMemory(m.dataUrl, dataUrlIsFolderBase, passportId);
        if (!(bytes(resolvedDataUrl).length <= 512)) revert EC(27);

        _passports[passportId] = Passport({
            passportId: passportId,
            contractVersion: CONTRACT_VERSION,
            creator: principalWallet,
            owner: principalWallet,
            creatorId: creatorId,
            year: m.core.year,
            month: m.core.month,
            title: m.core.title,
            domain: m.core.domain,
            objectType: OBJECT_DIGITAL,
            contentClass: m.core.contentClass,
            lifecycleStatus: m.core.lifecycleStatus,
            aiStatus: m.core.aiStatus,
            verificationMethod: m.core.verificationMethod,
            editionModel: m.core.editionModel,
            currentLocation: m.core.currentLocation,
            rightsNote: m.core.rightsNote,
            conditionNote: m.core.conditionNote,
            damageHistoryHash: m.core.damageHistoryHash,
            damageHistoryUrl: m.core.damageHistoryUrl,
            dataHash: m.dataHash,
            imageHash: m.imageHash,
            imageHash2: m.imageHash2,
            imageHash3: m.imageHash3,
            fileHash: m.fileHash,
            sealType: 0,
            sealHash: bytes32(0),
            nfcPublicKey: "",
            nfcModel: "",
            dataUrl: resolvedDataUrl,
            imageUrl: m.imageUrl,
            imageUrl2: m.imageUrl2,
            imageUrl3: m.imageUrl3,
            timestamp: block.timestamp,
            revoked: false,
            revokedAt: 0,
            revocationReasonHash: bytes32(0),
            auxCommitmentHash: m.auxCommitmentHash,
            auxCommitmentUri: m.auxCommitmentUri,
            ndppCommitmentHash: m.ndppCommitmentHash,
            ndppCommitmentUri: m.ndppCommitmentUri,
            mintAgent: mintAgentForPassport
        });

        _creatorPassports[principalWallet].push(passportId);

        emit PassportMinted(
            passportId,
            principalWallet,
            creatorId,
            m.core.title,
            m.core.domain,
            OBJECT_DIGITAL,
            m.core.contentClass,
            m.core.year,
            m.core.month,
            m.dataHash,
            0,
            "",
            block.timestamp,
            mintAgentForPassport
        );
    }

    function _mintPhysicalCommit(
        string memory creatorId,
        PhysicalMintInputs memory m,
        bool dataUrlIsFolderBase,
        address principalWallet,
        address mintAgentForPassport
    ) internal returns (string memory passportId) {
        passportId = _generatePassportId(m.core.year, m.core.month);
        string memory resolvedDataUrl = ODPPassportLib.resolveMintDataUrlMemory(m.dataUrl, dataUrlIsFolderBase, passportId);
        if (!(bytes(resolvedDataUrl).length <= 512)) revert EC(27);

        _passports[passportId] = Passport({
            passportId: passportId,
            contractVersion: CONTRACT_VERSION,
            creator: principalWallet,
            owner: principalWallet,
            creatorId: creatorId,
            year: m.core.year,
            month: m.core.month,
            title: m.core.title,
            domain: m.core.domain,
            objectType: OBJECT_PHYSICAL,
            contentClass: m.core.contentClass,
            lifecycleStatus: m.core.lifecycleStatus,
            aiStatus: m.core.aiStatus,
            verificationMethod: m.core.verificationMethod,
            editionModel: m.core.editionModel,
            currentLocation: m.core.currentLocation,
            rightsNote: m.core.rightsNote,
            conditionNote: m.core.conditionNote,
            damageHistoryHash: m.core.damageHistoryHash,
            damageHistoryUrl: m.core.damageHistoryUrl,
            dataHash: m.dataHash,
            imageHash: m.imageHash,
            imageHash2: m.imageHash2,
            imageHash3: m.imageHash3,
            fileHash: bytes32(0),
            sealType: m.sealType,
            sealHash: m.sealHash,
            nfcPublicKey: m.nfcPublicKey,
            nfcModel: m.nfcModel,
            dataUrl: resolvedDataUrl,
            imageUrl: m.imageUrl,
            imageUrl2: m.imageUrl2,
            imageUrl3: m.imageUrl3,
            timestamp: block.timestamp,
            revoked: false,
            revokedAt: 0,
            revocationReasonHash: bytes32(0),
            auxCommitmentHash: m.auxCommitmentHash,
            auxCommitmentUri: m.auxCommitmentUri,
            ndppCommitmentHash: m.ndppCommitmentHash,
            ndppCommitmentUri: m.ndppCommitmentUri,
            mintAgent: mintAgentForPassport
        });

        _creatorPassports[principalWallet].push(passportId);

        emit PassportMinted(
            passportId,
            principalWallet,
            creatorId,
            m.core.title,
            m.core.domain,
            OBJECT_PHYSICAL,
            m.core.contentClass,
            m.core.year,
            m.core.month,
            m.dataHash,
            m.sealType,
            m.nfcModel,
            block.timestamp,
            mintAgentForPassport
        );
    }

    function _mintMixedCommit(
        string memory creatorId,
        MixedMintInputs memory m,
        bool dataUrlIsFolderBase,
        address principalWallet,
        address mintAgentForPassport
    ) internal returns (string memory passportId) {
        passportId = _generatePassportId(m.core.year, m.core.month);
        string memory resolvedDataUrl = ODPPassportLib.resolveMintDataUrlMemory(m.dataUrl, dataUrlIsFolderBase, passportId);
        if (!(bytes(resolvedDataUrl).length <= 512)) revert EC(27);

        _passports[passportId] = Passport({
            passportId: passportId,
            contractVersion: CONTRACT_VERSION,
            creator: principalWallet,
            owner: principalWallet,
            creatorId: creatorId,
            year: m.core.year,
            month: m.core.month,
            title: m.core.title,
            domain: m.core.domain,
            objectType: OBJECT_MIXED,
            contentClass: m.core.contentClass,
            lifecycleStatus: m.core.lifecycleStatus,
            aiStatus: m.core.aiStatus,
            verificationMethod: m.core.verificationMethod,
            editionModel: m.core.editionModel,
            currentLocation: m.core.currentLocation,
            rightsNote: m.core.rightsNote,
            conditionNote: m.core.conditionNote,
            damageHistoryHash: m.core.damageHistoryHash,
            damageHistoryUrl: m.core.damageHistoryUrl,
            dataHash: m.dataHash,
            imageHash: m.imageHash,
            imageHash2: m.imageHash2,
            imageHash3: m.imageHash3,
            fileHash: m.fileHash,
            sealType: m.sealType,
            sealHash: m.sealHash,
            nfcPublicKey: m.nfcPublicKey,
            nfcModel: m.nfcModel,
            dataUrl: resolvedDataUrl,
            imageUrl: m.imageUrl,
            imageUrl2: m.imageUrl2,
            imageUrl3: m.imageUrl3,
            timestamp: block.timestamp,
            revoked: false,
            revokedAt: 0,
            revocationReasonHash: bytes32(0),
            auxCommitmentHash: m.auxCommitmentHash,
            auxCommitmentUri: m.auxCommitmentUri,
            ndppCommitmentHash: m.ndppCommitmentHash,
            ndppCommitmentUri: m.ndppCommitmentUri,
            mintAgent: mintAgentForPassport
        });

        _creatorPassports[principalWallet].push(passportId);

        emit PassportMinted(
            passportId,
            principalWallet,
            creatorId,
            m.core.title,
            m.core.domain,
            OBJECT_MIXED,
            m.core.contentClass,
            m.core.year,
            m.core.month,
            m.dataHash,
            m.sealType,
            m.nfcModel,
            block.timestamp,
            mintAgentForPassport
        );
    }

    function mintPhysical(
        PhysicalMintInputs calldata m,
        bool dataUrlIsFolderBase,
        string calldata mintOnBehalfOfCreatorId
    ) external returns (string memory passportId) {
        (string memory creatorId, address principalWallet, address mintAgentAddr) = _beginMint(mintOnBehalfOfCreatorId);
        ODPPassportLib.validatePhysicalMintForMint(m);
        _requireUtcYearMonth(m.core.year, m.core.month);
        return _mintPhysicalCommit(creatorId, m, dataUrlIsFolderBase, principalWallet, mintAgentAddr);
    }

    function mintDigital(
        DigitalMintInputs calldata dm,
        bool dataUrlIsFolderBase,
        string calldata mintOnBehalfOfCreatorId
    ) external returns (string memory passportId) {
        (string memory creatorId, address principalWallet, address mintAgentAddr) = _beginMint(mintOnBehalfOfCreatorId);
        ODPPassportLib.validateDigitalMintInputs(dm);
        _requireUtcYearMonth(dm.core.year, dm.core.month);
        return _mintDigitalCommit(creatorId, dm, dataUrlIsFolderBase, principalWallet, mintAgentAddr);
    }

    function mintMixed(
        MixedMintInputs calldata mm,
        bool dataUrlIsFolderBase,
        string calldata mintOnBehalfOfCreatorId
    ) external returns (string memory passportId) {
        (string memory creatorId, address principalWallet, address mintAgentAddr) = _beginMint(mintOnBehalfOfCreatorId);
        ODPPassportLib.validateMixedMintInputs(mm);
        _requireUtcYearMonth(mm.core.year, mm.core.month);
        return _mintMixedCommit(creatorId, mm, dataUrlIsFolderBase, principalWallet, mintAgentAddr);
    }

    // ─── Passport — Update ────────────────────────────────────────────────────

    function _canUpdatePassportUrls(Passport storage p) internal view returns (bool) {
        if (msg.sender == p.creator || msg.sender == p.owner) return true;
        address rel = relationsSatellite;
        if (rel == address(0)) return false;
        (address agent, uint256 expiresAt) = IODPRelationsLookup(rel).getCreatorPublishingDelegation(p.creator);
        return agent == msg.sender && expiresAt > block.timestamp;
    }

    function _canUpdatePassportState(Passport storage p) internal view returns (bool) {
        return msg.sender == p.creator || msg.sender == p.owner || msg.sender == governance;
    }

    /**
     * Update hosting URLs only — dataUrl and imageUrl.
     * Use this when moving the hosted `.odpass` bundle or image to a new host.
     *
     * ALL HASHES ARE IMMUTABLE after minting:
     *   dataHash, imageHash, fileHash, sealHash — cannot change ever.
     *
     * The caller must provide confirmedDataHash matching the on-chain dataHash.
     * This proves the caller knows the original content and prevents accidental
     * URL mistakes that would make the passport appear tampered.
     *
     * Note: this does NOT protect against a stolen wallet — dataHash is public
     * on-chain, so anyone with wallet access can read and pass it. This is a
     * UX safeguard, not a security mechanism.
     *
     * Authorized callers: passport **creator** or **owner**, or the **creator’s active publishing agent**
     * (`delegateCreatorPublishing` / `getCreatorPublishingDelegation`).
     *
     * Folder-base mint (`dataUrlIsFolderBase` on mint) only affects the **initial** stored URL.
     * This function always sets **literal** `newDataUrl` / `newImageUrl` (no folder resolution here).
     *
     * @param confirmedDataHash  Must equal the on-chain dataHash. Prevents
     *                           accidental URL updates pointing to wrong content.
     */
    function updatePassportUrls(
        string  calldata passportId,
        string  calldata newDataUrl,
        string  calldata newImageUrl,
        bytes32          confirmedDataHash
    ) external {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!_canUpdatePassportUrls(p)) revert EC(26);
        if (!(p.dataHash == confirmedDataHash)) revert EC(25);
        if (!(bytes(newDataUrl).length <= 512)) revert EC(24);
        if (!(bytes(newImageUrl).length <= 512)) revert EC(23);

        // Only primary JSON + primary image URLs — hashes are immutable (extra image URLs unchanged here).
        p.dataUrl  = newDataUrl;
        p.imageUrl = newImageUrl;

        emit PassportUrlsUpdated(passportId, newDataUrl, newImageUrl);
    }

    /**
     * Update optional second commitment (e.g. COA PDF) and its URL hint. Does not change `dataHash` / image hashes.
     * @dev Only **creator** or **governance**. Revoked passports cannot be updated. `(bytes32(0), "")` clears the aux slot.
     */
    function updatePassportAuxCommitment(
        string calldata passportId,
        bytes32 newHash,
        string calldata newUri
    ) external {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!(msg.sender == p.creator || msg.sender == governance)) revert EC(67);
        ODPPassportLib.validateAuxCommitmentFields(newHash, newUri);
        p.auxCommitmentHash = newHash;
        p.auxCommitmentUri = newUri;
        emit PassportAuxCommitmentUpdated(passportId, newHash, newUri, msg.sender, block.timestamp);
    }

    /**
     * Update optional NDPP / offline-public commitment and its URL hint. Does not change `dataHash` / image hashes.
     * @dev Only **creator** or **governance**. Revoked passports cannot be updated. `(bytes32(0), "")` clears the NDPP slot.
     */
    function updatePassportNdppCommitment(
        string calldata passportId,
        bytes32 newHash,
        string calldata newUri
    ) external {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!(msg.sender == p.creator || msg.sender == governance)) revert EC(67);
        ODPPassportLib.validateNdppCommitmentFields(newHash, newUri);
        p.ndppCommitmentHash = newHash;
        p.ndppCommitmentUri = newUri;
        emit PassportNdppCommitmentUpdated(passportId, newHash, newUri, msg.sender, block.timestamp);
    }

    function updatePassportStatus(string calldata passportId, uint8 newLifecycleStatus) external {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!_canUpdatePassportState(p)) revert EC(98);
        ODPPassportLib.validateLifecycleStatus(newLifecycleStatus);
        p.lifecycleStatus = newLifecycleStatus;
        emit PassportStatusUpdated(passportId, newLifecycleStatus, msg.sender, block.timestamp);
    }

    function updatePassportLocation(string calldata passportId, string calldata newLocation) external {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!_canUpdatePassportState(p)) revert EC(98);
        if (!(bytes(newLocation).length <= 256)) revert EC(94);
        p.currentLocation = newLocation;
        emit PassportLocationUpdated(passportId, newLocation, msg.sender, block.timestamp);
    }

    function updatePassportRights(string calldata passportId, string calldata newRightsNote) external {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!_canUpdatePassportState(p)) revert EC(98);
        if (!(bytes(newRightsNote).length <= 256)) revert EC(95);
        p.rightsNote = newRightsNote;
        emit PassportRightsUpdated(passportId, newRightsNote, msg.sender, block.timestamp);
    }

    function updatePassportCondition(
        string calldata passportId,
        string calldata newConditionNote,
        bytes32 newDamageHistoryHash,
        string calldata newDamageHistoryUrl
    ) external {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!_canUpdatePassportState(p)) revert EC(98);
        if (!(bytes(newConditionNote).length <= 256)) revert EC(96);
        ODPPassportLib.validateDamageHistoryFields(newDamageHistoryHash, newDamageHistoryUrl);
        p.conditionNote = newConditionNote;
        p.damageHistoryHash = newDamageHistoryHash;
        p.damageHistoryUrl = newDamageHistoryUrl;
        emit PassportConditionUpdated(
            passportId,
            newConditionNote,
            newDamageHistoryHash,
            newDamageHistoryUrl,
            msg.sender,
            block.timestamp
        );
    }

    /// Current owner (starts as creator) may transfer the passport record to a new wallet.
    function transferPassport(string calldata passportId, address newOwner) external {
        if (!(newOwner != address(0))) revert EC(22);
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!(p.owner == msg.sender)) revert EC(19);
        p.owner = newOwner;
        emit PassportTransferred(passportId, msg.sender, newOwner, block.timestamp);
    }

    /**
     * Irreversible passport revocation. Creator or governance may revoke.
     * reasonHash should be keccak256(utf8(reason)) for verifiers; full text may live off-chain.
     */
    function revokePassport(string calldata passportId, bytes32 reasonHash) external {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(18);
        if (!(msg.sender == p.creator || msg.sender == governance)) revert EC(17);
        if (!(reasonHash != bytes32(0))) revert EC(16);
        p.revoked = true;
        p.revokedAt = block.timestamp;
        p.revocationReasonHash = reasonHash;
        emit PassportRevoked(passportId, msg.sender, reasonHash, block.timestamp);
    }

    // ─── Passport — Read ──────────────────────────────────────────────────────

    function getPassportHeader(string calldata passportId)
        external view returns (PassportHeaderView memory out)
    {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        out = PassportHeaderView({
            passportId: p.passportId,
            contractVersion: p.contractVersion,
            creator: p.creator,
            owner: p.owner,
            creatorId: p.creatorId,
            year: p.year,
            month: p.month,
            title: p.title,
            domain: p.domain,
            objectType: p.objectType
        });
    }

    function getPassportClassification(string calldata passportId)
        external view returns (PassportClassificationView memory out)
    {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        out = PassportClassificationView({
            contentClass: p.contentClass,
            lifecycleStatus: p.lifecycleStatus,
            aiStatus: p.aiStatus,
            verificationMethod: p.verificationMethod,
            editionModel: p.editionModel,
            timestamp: p.timestamp,
            revoked: p.revoked,
            revokedAt: p.revokedAt,
            revocationReasonHash: p.revocationReasonHash,
            mintAgent: p.mintAgent
        });
    }

    function getPassportMedia(string calldata passportId)
        external view returns (PassportMediaView memory out)
    {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        out = PassportMediaView({
            dataHash: p.dataHash,
            dataUrl: p.dataUrl,
            imageHash: p.imageHash,
            imageUrl: p.imageUrl,
            imageHash2: p.imageHash2,
            imageUrl2: p.imageUrl2,
            imageHash3: p.imageHash3,
            imageUrl3: p.imageUrl3,
            fileHash: p.fileHash
        });
    }

    function getPassportPhysical(string calldata passportId)
        external view returns (PassportPhysicalView memory out)
    {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        out = PassportPhysicalView({
            sealType: p.sealType,
            sealHash: p.sealHash,
            nfcPublicKey: p.nfcPublicKey,
            nfcModel: p.nfcModel
        });
    }

    function getPassportState(string calldata passportId)
        external view returns (PassportStateView memory out)
    {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        out = PassportStateView({
            currentLocation: p.currentLocation,
            rightsNote: p.rightsNote,
            conditionNote: p.conditionNote,
            damageHistoryHash: p.damageHistoryHash,
            damageHistoryUrl: p.damageHistoryUrl,
            auxCommitmentHash: p.auxCommitmentHash,
            auxCommitmentUri: p.auxCommitmentUri,
            ndppCommitmentHash: p.ndppCommitmentHash,
            ndppCommitmentUri: p.ndppCommitmentUri
        });
    }

    function getPassportsByCreatorPaged(address creator, uint256 offset, uint256 limit)
        external
        view
        returns (string[] memory result, uint256 total)
    {
        return _stringArraySlice(_creatorPassports[creator], offset, limit);
    }

    // ─── Internal: validation ─────────────────────────────────────────────────

    function _requireRegistered() internal view returns (string memory creatorId) {
        creatorId = _walletToCreatorId[msg.sender];
        if (!(bytes(creatorId).length > 0)) revert EC(3);
    }

    /**
     * @return creatorId Profile id written on the passport.
     * @return principalWallet Issuer wallet (`Passport.creator` / initial `owner`).
     * @return mintAgentAddr `address(0)` if principal mints; else `msg.sender` (delegate).
     */
    function _resolveMintPrincipal(string calldata mintOnBehalfOfCreatorId)
        internal
        view
        returns (string memory creatorId, address principalWallet, address mintAgentAddr)
    {
        address actor = msg.sender;
        address router = extensionRouter;
        if (router != address(0) && msg.sender == router) {
            actor = tx.origin;
        }
        if (bytes(mintOnBehalfOfCreatorId).length == 0) {
            creatorId = _walletToCreatorId[actor];
            if (!(bytes(creatorId).length > 0)) revert EC(3);
            return (creatorId, actor, address(0));
        }
        creatorId = mintOnBehalfOfCreatorId;
        CreatorRecord storage cr = _creators[creatorId];
        if (!(bytes(cr.creatorId).length > 0)) revert EC(2);
        principalWallet = cr.wallet;
        if (actor == principalWallet) {
            return (creatorId, principalWallet, address(0));
        }
        address rel = relationsSatellite;
        if (rel == address(0)) revert EC(72);
        if (!(IODPRelationsLookup(rel).mintAgentForCreator(creatorId) == actor)) revert EC(72);
        return (creatorId, principalWallet, actor);
    }

    /** Enforce registration (caller or agent path), monthly limit on **principal** wallet, increment counter. */
    function _beginMint(string calldata mintOnBehalfOfCreatorId)
        internal
        returns (string memory creatorId, address principalWallet, address mintAgentAddr)
    {
        (creatorId, principalWallet, mintAgentAddr) = _resolveMintPrincipal(mintOnBehalfOfCreatorId);
        _checkAndIncrementMintLimit(creatorId, principalWallet);
    }

    /// @dev `year`/`month` must match Gregorian UTC calendar of `block.timestamp` (ODP-ID prefix binds to mint month).
    function _requireUtcYearMonth(uint32 year, uint8 month) private view {
        (uint32 cy, uint8 cm) = ODPPassportLib.utcYearMonthFromTimestamp(block.timestamp);
        if (!(year == cy && month == cm)) revert EC(68);
    }

    function _isValidType(bytes1 t) internal pure returns (bool) {
        return t == TYPE_C || t == TYPE_B || t == TYPE_P || t == TYPE_M;
    }

    /**
     * Check monthly mint limit and increment counter (C/B only; P and M are unlimited).
     * Counts against **principal** issuer wallet (so an agent consumes the artist’s tier quota).
     * Resets on calendar month boundary (yearMonth key changes).
     */
    function _checkAndIncrementMintLimit(string memory creatorId, address principalWallet) internal {
        bytes1 t = _creators[creatorId].typePrefix;
        if (t == TYPE_P || t == TYPE_M) {
            return;
        }
        uint32 limit = (t == TYPE_B) ? MONTHLY_LIMIT_B : MONTHLY_LIMIT_C;
        uint32 ym = _currentYearMonth();
        uint32 count = _mintCount[principalWallet][ym];
        if (!(count < limit)) revert EC(1);
        _mintCount[principalWallet][ym] = count + 1;
    }

    function _currentYearMonth() internal view returns (uint32) {
        uint32 year = _currentYear();
        uint8 month = _currentMonth();
        return year * 100 + uint32(month);
    }

    function _currentYear() internal view returns (uint32) {
        return uint32(1970 + block.timestamp / 31_556_952);
    }

    function _currentMonth() internal view returns (uint8) {
        // Calendar math on block.timestamp, not randomness (triaged: not security-critical).
        // slither-disable-next-line weak-prng
        uint256 secsInYear = block.timestamp % 31_556_952;
        uint256 m = secsInYear / 2_629_746 + 1;
        if (m > 12) m = 12;
        return uint8(m);
    }

    // ─── Internal: ID generation ──────────────────────────────────────────────

    /**
     * Generate a unique profile ID number (0–999,999,999,999).
     * Uses keccak256 entropy with nonce. Retries on collision (max 25 attempts).
     */
    function _generateCreatorNumber() internal returns (uint64) {
        uint256 baseNonce = _creatorNonce;
        for (uint i = 0; i < 25; i++) {
            // Combine multiple sources for better unpredictability.
            // Note: on-chain entropy is never truly random — IDs are not
            // security-critical (no funds at stake), so this is acceptable.
            // slither-disable-next-line weak-prng
            uint64 n = uint64(uint256(keccak256(abi.encodePacked(
                block.timestamp,
                block.prevrandao,   // replaces block.difficulty post-Merge
                msg.sender,
                baseNonce + i,
                gasleft()
            ))) % 1_000_000_000_000);
            if (!_creatorNumberTaken[n]) {
                _creatorNonce = baseNonce + i + 1;
                return n;
            }
        }
        revert EC(62);
    }

    /**
     * Generate a unique Passport ID number (0–999,999,999) for year+month.
     * Uses keccak256 entropy with nonce. Retries on collision (max 25 attempts).
     */
    function _generatePassportId(uint32 year, uint8 month)
        internal returns (string memory)
    {
        uint32 key = uint32(year) * 100 + uint32(month);
        uint256 baseNonce = _passportNonce;
        for (uint i = 0; i < 25; i++) {
            // Human-readable ID entropy, not security randomness (see SECURITY NOTES header).
            // slither-disable-next-line weak-prng
            uint32 n = uint32(uint256(keccak256(abi.encodePacked(
                block.timestamp,
                block.prevrandao,
                msg.sender,
                baseNonce + i,
                key,
                gasleft()
            ))) % 1_000_000_000);
            if (!_passportNumberTaken[key][n]) {
                _passportNonce = baseNonce + i + 1;
                _passportNumberTaken[key][n] = true;
                return ODPPassportLib.formatOdpPassportId(year, month, n);
            }
        }
        revert EC(61);
    }

    // Approximate calendar from block.timestamp: rate-limit buckets only (±1 month drift acceptable).

}
