/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IODPRegistryForProofs {
      
    export type CreatorRecordStruct = {creatorId: string, wallet: AddressLike, typePrefix: BytesLike, timestamp: BigNumberish}

    export type CreatorRecordStructOutput = [creatorId: string, wallet: string, typePrefix: string, timestamp: bigint] & {creatorId: string, wallet: string, typePrefix: string, timestamp: bigint }
  

    export type PassportClassificationViewStruct = {contentClass: BigNumberish, lifecycleStatus: BigNumberish, aiStatus: BigNumberish, verificationMethod: BigNumberish, editionModel: BigNumberish, timestamp: BigNumberish, revoked: boolean, revokedAt: BigNumberish, revocationReasonHash: BytesLike, mintAgent: AddressLike}

    export type PassportClassificationViewStructOutput = [contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint, timestamp: bigint, revoked: boolean, revokedAt: bigint, revocationReasonHash: string, mintAgent: string] & {contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint, timestamp: bigint, revoked: boolean, revokedAt: bigint, revocationReasonHash: string, mintAgent: string }
  
    }

  export interface IODPRegistryForProofsInterface extends Interface {
    getFunction(nameOrSignature: "getCreator" | "getCreatorByWallet" | "getPassportClassification"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getCreator', values: [string]): string;
encodeFunctionData(functionFragment: 'getCreatorByWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPassportClassification', values: [string]): string;

    decodeFunctionResult(functionFragment: 'getCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorByWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportClassification', data: BytesLike): Result;
  }

  

  export interface IODPRegistryForProofs extends BaseContract {
    
    connect(runner?: ContractRunner | null): IODPRegistryForProofs;
    waitForDeployment(): Promise<this>;

    interface: IODPRegistryForProofsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getCreator: TypedContractMethod<
      [creatorId: string, ],
      [IODPRegistryForProofs.CreatorRecordStructOutput],
      'view'
    >
    

    
    getCreatorByWallet: TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >
    

    
    getPassportClassification: TypedContractMethod<
      [passportId: string, ],
      [IODPRegistryForProofs.PassportClassificationViewStructOutput],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getCreator'): TypedContractMethod<
      [creatorId: string, ],
      [IODPRegistryForProofs.CreatorRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorByWallet'): TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportClassification'): TypedContractMethod<
      [passportId: string, ],
      [IODPRegistryForProofs.PassportClassificationViewStructOutput],
      'view'
    >;

    

    filters: {
      
    };
  }