// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./ODPErrors.sol";
import {DigitalMintInputs, PhysicalMintInputs} from "./ODPPassportTypes.sol";
import "./ODPPassportLib.sol";

/**
 * Object Digital Passport — Smart Contract
 * @author Andrei Chernikov
 * Specification v0.4 (reference branch)
 * License: MIT
 *
 * Deployed on: Polygon PoS (chain ID 137)
 * Testnet:     Polygon Amoy (chain ID 80002)
 *
 * Three registries in one contract:
 *   1. Creator Registry  — C / B / P / M identifiers
 *   2. Passport Registry — physical and digital object records
 *   3. Proof Registry    — institution attestations
 *
 * All IDs are randomly generated by the contract.
 * A registered profile ID (`creatorId`) is mandatory for minting and proof submission.
 *
 * IMMUTABILITY:
 *   This contract is not upgradeable by design.
 *   No owner. No admin. No pause function. No selfdestruct.
 *   Rules cannot change after deployment.
 *   Protocol updates require a new contract (v0.2, v0.3, etc.).
 *
 * VERSIONING (normative detail: SPEC.md):
 *   Reference lines v0.1, v0.2, and v0.3 are separate registries — not backward compatible
 *   (different address, bytecode, ABI). Integrators must not treat them as drop-in replacements.
 *   The v0.3 line is documented in SPEC as aligned toward a future stable v1 (migration to be
 *   defined in v1); this is design intent, not an in-place upgrade guarantee.
 *   v0.4 reference: v0.3 feature set + satellite counterfeit concern (SPEC), NFC NTAG424DNA_TT only;
 *   ABI names the Passport ID field `passportId` (structs, events, external API) — same spec line / packed byte as earlier v0.4 `humanId` deployments.
 *   v0.3 added: owner/transfer, account-scoped publishing agent for hosted URLs, revocation,
 *   extra image hashes, P-affiliation detach + timestamps, governance (revocation),
 *   optional aux commitment + IODPExtension mint routes (digital/physical).
 *   Type-definition governance is off-chain / SPEC where noted (saves bytecode).
 *
 * SECURITY NOTES:
 *   - v0.2+: no protocol fee — native token only pays network gas (no POL routed to fee burn)
 *   - Extension mint uses staticcalls to registered `IODPExtension` (view) then state writes — no reentrancy loop into core
 *   - Solidity 0.8.20 — overflow/underflow protection built in
 *   - Access control enforced via `if (!(…)) revert EC(n);` on write paths
 *   - On-chain randomness (block.prevrandao + gasleft) is not
 *     cryptographically secure but is acceptable here since IDs
 *     carry no financial value — only human-readability
 *   - NFC: only NTAG424DNA_TT — issuer declares model; verify is off-chain per SPEC
 *   - Proof institutions (P) and museums (M) are open registration — verifiers must warn
 *     users to confirm P/M-type IDs on official institution websites
 *   - Mint agent (v0.3): optional two-step handshake — agent `requestMintAgentRole(principalCreatorId)`,
 *     principal `confirmMintAgentRole(agent)` — then agent may mint with `mintOnBehalfOfCreatorId`;
 *     `Passport.creator` / `owner` are the principal wallet; `Passport.mintAgent` records who sent the tx (0 = self)
 *   - Creator is trusted to physically install the correct chip model
 *     The contract cannot verify hardware — only the declared model
 *   - Anti-spam: monthly mint-rate limit (no protocol fee — gas only)
 *   - Rate limit (per wallet, per calendar month): C = 1000, B = 100_000, P/M = unlimited
 *   - Passport namespace: 100M IDs per year+month (previously 10M)
 *   - P-type whitelist is intentionally off-chain — see external repos
 *
 * SOURCE CODE:
 *   Published at: https://github.com/object-digital-passport/object-digital-passport
 *   Anyone can read, verify, fork, or deploy their own instance.
 *
 * DEPLOY (EIP-170):
 *   Deploy linked library `ODPPassportLib` first, then deploy this contract with compiler linker
 *   metadata pointing at that library address (see `deploy/scripts/deploy.js`).
 */
/**
 * IODPExtension — interface for **mint-class** extension contracts (governance-registered via `setMintExtension`).
 *
 * The `mintClass` byte in `typeToExtension` is **not** the creator profile prefix (C/B/P/M).
 * Those profile letters are fixed at `registerCreator`. `mintClass` selects an alternate **mint pipeline**
 * (e.g. custom bytes like `"V"` or `"G"` in documentation) implemented by a separate contract that
 * implements this interface.
 *
 * Digital `normalize` output: **13-tuple** ending with `auxCommitmentHash` + `auxCommitmentUri` (see `ODPPassportLib.validateAuxCommitmentFields`).
 * Physical `normalize` output: **16-tuple** — physical mint params + same aux pair (see `mintPhysicalViaExtension` NatSpec).
 */
interface IODPExtension {
    /// Validate type-specific data. Reverts if invalid.
    function validate(bytes calldata data) external view;
    /// @dev Return `abi.encode` of either the **digital** 13-tuple or **physical** 16-tuple documented on `mintDigitalViaExtension` / `mintPhysicalViaExtension`.
    function normalize(bytes calldata data) external view returns (bytes memory);
}

contract ObjectDigitalPassport {

    // ─── Constants ────────────────────────────────────────────────────────────

    bytes1 constant TYPE_C = "C";
    bytes1 constant TYPE_B = "B";
    bytes1 constant TYPE_P = "P";
    bytes1 constant TYPE_M = "M";

    string constant OBJECT_PHYSICAL = "physical";
    string constant OBJECT_DIGITAL  = "digital";

    // On-chain spec line (variant: two uint8s, human-readable as major.minor).
    // Not `public` — each public constant adds a getter (~bytecode budget, EIP-170). Use `CONTRACT_VERSION` / 16 and % 16.
    uint8 internal constant SPEC_MAJOR = 0;
    uint8 internal constant SPEC_MINOR = 4;

    /// Packed byte in `Passport.contractVersion`: `SPEC_MAJOR * 16 + SPEC_MINOR` (each < 16).
    /// **v0.4** uses packed byte **4**. New bytecode uses ABI name `passportId`; some earlier v0.4 deployments used `humanId` (integrators: match ABI to bytecode).
    uint8 public constant CONTRACT_VERSION = SPEC_MAJOR * 16 + SPEC_MINOR;

    // Anti-spam: per-wallet, per-calendar-month mint caps (no protocol fee). Tier follows profile ID prefix (C/B/P/M).
    uint32 internal constant MONTHLY_LIMIT_C = 1000;
    uint32 internal constant MONTHLY_LIMIT_B = 100_000;

    // ─── Structs ──────────────────────────────────────────────────────────────

    struct CreatorRecord {
        string  creatorId;    // "C-482-930-174-005"
        address wallet;
        bytes1  typePrefix;   // "C", "B", "P", or "M" — stored as bytes1 for gas efficiency
        uint256 timestamp;
    }

    struct Passport {
        string  passportId;       // Passport ID (SPEC); ODP-… string; ABI name passportId
        uint8   contractVersion; // packed SPEC_MAJOR/SPEC_MINOR (see CONTRACT_VERSION) at mint
        address creator;       // immutable issuer wallet at mint
        address owner;         // current holder; starts as creator; changes via transferPassport
        string  creatorId;     // Profile ID (SPEC); mandatory
        uint32  year;          // uint32 supports any year from 1 to 4,294,967,295
        uint8   month;
        /// v0.3 mint path: only OBJECT_PHYSICAL / OBJECT_DIGITAL. Subtypes and industry labels → SPEC + `passport.json` + `dataHash`.
        /// A new top-level on-chain `objectType` string (third branch in storage/events) requires a protocol/contract line, not an implicit upgrade.
        string  objectType;    // "physical" or "digital"
        /// Commitment to canonical `passport.json` (SPEC §10). New JSON keys need no on-chain schema:
        /// evolve **SPEC** + canonicalization for **new** mints only; `dataHash` is **immutable** after mint, so
        /// the hashed byte string for an existing passport cannot gain new integrity-bound fields without breaking verify.
        /// Optional UI-only or manifest-only fields live off this anchor. Future lines may add auxiliary commitments if needed.
        bytes32 dataHash;      // SHA-256 of minified passport.json
        bytes32 imageHash;     // SHA-256 of primary image. bytes32(0) = none
        bytes32 imageHash2;    // optional 2nd image (max 3 on-chain hashes total)
        bytes32 imageHash3;    // optional 3rd image
        bytes32 fileHash;      // SHA-256 of digital file. bytes32(0) if physical
        uint8   sealType;      // 1=NFC, 2=numbered, 3=both. 0 if digital
        bytes32 sealHash;      // SHA-256 of seal object. bytes32(0) if digital
        bytes   nfcPublicKey;  // NFC chip public key. empty if no NFC seal
        string  nfcModel;      // "NTAG424DNA_TT" if NFC (SPEC). empty if no NFC seal
        string  dataUrl;
        string  imageUrl;
        string  imageUrl2;     // optional URL hints for extra images
        string  imageUrl3;
        uint256 timestamp;
        bool    revoked;       // passport revoked (creator or governance)
        uint256 revokedAt;
        bytes32 revocationReasonHash; // keccak256 of UTF-8 reason; 0 if not revoked
        /// Optional second commitment (e.g. PDF COA); independent of `dataHash`. Mutable by creator or governance.
        bytes32 auxCommitmentHash;
        string  auxCommitmentUri; // optional HTTPS hint; max 512 when hash non-zero; both zero when unused
        /// Wallet that executed the mint for `creator`’s profile; `address(0)` = principal minted themselves.
        address mintAgent;
    }

    struct ProofRecord {
        string  proofId;         // "PRF-2031-03-7392018"
        uint8   contractVersion; // packed SPEC_MAJOR/SPEC_MINOR at submission
        string  prover;          // Profile ID of P- or M-type institution
        string  passportId;         // attested passport
        bytes32 noteHash;        // SHA-256 of attached document. bytes32(0) = none
        string  noteUrl;
        uint256 timestamp;
    }

    // ─── Storage ──────────────────────────────────────────────────────────────

    // Creator Registry
    mapping(string  => CreatorRecord) private _creators;
    mapping(address => string)        private _walletToCreatorId;
    mapping(uint64  => bool)          private _creatorNumberTaken;
    uint256 private _creatorNonce;

    // Passport Registry
    // key = year * 100 + month → set of random numbers taken
    mapping(uint32 => mapping(uint32 => bool)) private _passportNumberTaken;
    mapping(string => Passport)   private _passports;
    mapping(address => string[])  private _creatorPassports;
    uint256 private _passportNonce;

    // Proof Registry
    mapping(uint32 => mapping(uint32 => bool)) private _proofNumberTaken;
    mapping(string => ProofRecord)  private _proofs;
    mapping(string => string[])     private _passportProofs;
    mapping(string => string[])     private _institutionProofs;
    uint256 private _proofNonce;

    // Rate limiting — mints per wallet per calendar month (C/B tiers; P skips limit)
    // key = address → (yearMonth uint32 e.g. 202603) → count
    mapping(address => mapping(uint32 => uint32)) private _mintCount;

    // P-affiliation (one-level): child P -> exactly one parent P.
    // Handshake is two-step to reduce spam:
    // 1) child proposes parent, 2) parent confirms.
    mapping(bytes32 => bool)      private _pendingPAffiliation; // key = keccak256(parentId, childId)
    mapping(string  => string)    private _pParentOf;           // childPId -> parentPId (active)
    mapping(string  => string[])  private _pChildrenOf;         // parentPId -> childPId[]

    // Hard caps (v0.2 anti-growth limits)
    uint16 private constant MAX_P_ACTIVE_CHILDREN_PER_PARENT = 100;
    uint16 private constant MAX_P_PENDING_PARENTS_PER_CHILD  = 100;
    mapping(string => uint16) private _pActiveChildrenCountByParent; // parentPId -> active children count
    mapping(string => uint16) private _pPendingParentsCountByChild;   // childPId -> pending parent requests count

    /// When affiliation became active (parent confirmed). 0 if never linked.
    mapping(string => uint256) private _pAffiliationJoinedAt;
    /// Non-zero after detach while child has no active parent (cleared on new confirm).
    mapping(string => uint256) private _pAffiliationDetachedAt;
    /// Parent P id at time of last detach (for verifier audit when active parent is empty).
    mapping(string => string)  private _pLastDetachedParent;

    struct DelegationInfo {
        address agent;
        uint256 expiresAt;
    }

    /// One optional publishing agent per **registered creator wallet** (the issuer account). When active, that
    /// agent may call `updatePassportUrls` for any passport with `p.creator == creatorWallet` (hash check unchanged).
    mapping(address => DelegationInfo) private _creatorPublishDelegation;

    /// Governance address (multisig / DAO): may revoke passports alongside creator.
    /// Type-definition governance is documented in SPEC; on-chain timelock registry was omitted for bytecode size.
    address public governance;

    /// Principal profile ID → active mint-agent wallet (at most one). Public getter: `mintAgentForCreator(string)`.
    mapping(string => address) public mintAgentForCreator;
    /// Pending requests: `mintAgentDelegationPending(keccak256(abi.encodePacked(principalCreatorId, agent)))`.
    mapping(bytes32 => bool) public mintAgentDelegationPending;

    // Mint-class byte → extension. NOT creator profile prefix (C/B/P/M).
    mapping(bytes1 => address) public typeToExtension;

    uint8 private constant EXT_MINT_KIND_DIGITAL  = 0;
    uint8 private constant EXT_MINT_KIND_PHYSICAL = 1;

    // ── Freeze (v0.x only) ────────────────────────────────────────────────────────
    // Registry-wide freeze: deployer-only, irreversible. Planned stable v1 omits this mechanism (see docs/IDEAS_V1.md).
    // When migrating, this v0.x contract may be frozen to stop new writes; frozen = historical archive; reads unchanged.
    // Only the deployer address can freeze. Cannot be unfrozen.
    address public immutable deployer;
    bool    public frozen;

    modifier notFrozen() {
        if (!(!frozen)) revert EC(59);
        _;
    }

    // ─── Events ───────────────────────────────────────────────────────────────

    event CreatorRegistered(
        string  indexed creatorId,
        address indexed wallet,
        bytes1          typePrefix,
        uint256         timestamp
    );

    event PassportMinted(
        string  indexed passportId,
        address indexed creator,
        string          creatorId,
        string          objectType,
        uint32          year,
        uint8           month,
        bytes32         dataHash,
        uint8           sealType,   // 0=digital, 1=NFC, 2=numbered, 3=both
        string          nfcModel,   // "NTAG424DNA_TT" or "" if no NFC
        uint256         timestamp,
        address         mintAgent    // address(0) if principal called mint; else delegate wallet
    );

    /// Mint-agent lifecycle: kind 0=request pending, 1=request cancelled, 2=role activated, 3=role removed (revoke/renounce/replace).
    event MintAgentUpdate(string indexed principalCreatorId, address indexed agent, uint8 kind, uint256 timestamp);

    event PassportUrlsUpdated(
        string indexed passportId,
        string         newDataUrl,
        string         newImageUrl
    );

    event ProofSubmitted(
        string  indexed proofId,
        string  indexed passportId,
        string  indexed prover,
        uint256         timestamp
    );

    event ContractFrozen(uint256 timestamp);

    event PAffiliationProposed(
        string indexed parentPId,
        string indexed childPId,
        uint256 timestamp
    );

    event PAffiliationConfirmed(
        string indexed parentPId,
        string indexed childPId,
        uint256 timestamp
    );

    event PAffiliationDetached(
        string indexed parentPId,
        string indexed childPId,
        uint256 timestamp
    );

    event PassportTransferred(
        string  indexed passportId,
        address indexed from,
        address indexed to,
        uint256 timestamp
    );

    event CreatorPublishingDelegated(address indexed creator, address indexed agent, uint256 expiresAt);

    event CreatorPublishingDelegationRevoked(address indexed creator, uint256 timestamp);

    event PassportRevoked(
        string  indexed passportId,
        address indexed revokedBy,
        bytes32 reasonHash,
        uint256 timestamp
    );

    event GovernanceTransferred(address indexed previous, address indexed next, uint256 timestamp);

    event PassportAuxCommitmentUpdated(
        string  passportId,
        bytes32 newHash,
        string  newUri,
        address updatedBy,
        uint256 timestamp
    );

    /// @dev `kind`: 0 = digital extension mint, 1 = physical extension mint. Emitted with `PassportMinted`.
    event ExtensionMintUsed(bytes1 indexed mintClass, uint8 indexed kind, string passportId);

    // ─── Constructor ──────────────────────────────────────────────────────────

    constructor() {
        deployer = msg.sender;
        governance = msg.sender;
    }

    // ─── Freeze ───────────────────────────────────────────────────────────────

    /**
     * Freeze this contract — no new records can be created after this.
     * Existing data remains readable forever.
     * v0.x only: the planned stable v1 protocol line does not include registry-wide `freeze()` (see docs/IDEAS_V1.md).
     * May be used when sunsetting this deployment; only the original deployer can freeze.
     */
    function freeze() external {
        if (!(msg.sender == deployer)) revert EC(58);
        if (!(!frozen)) revert EC(57);
        frozen = true;
        emit ContractFrozen(block.timestamp);
    }

    /// Governance may be a multisig or DAO-controlled address off-chain.
    function transferGovernance(address newGovernance) external {
        if (!(msg.sender == governance)) revert EC(56);
        if (!(newGovernance != address(0))) revert EC(55);
        address prev = governance;
        governance = newGovernance;
        emit GovernanceTransferred(prev, newGovernance, block.timestamp);
    }

    /// @notice Register or remove an `IODPExtension` for `mintClass`. Only `governance`. `extension == address(0)` clears.
    /// @dev Forbidden `mintClass` values: same bytes as creator profile prefixes **C**, **B**, **P**, **M** (ASCII).
    function setMintExtension(bytes1 mintClass, address extension) external notFrozen {
        if (!(msg.sender == governance)) revert EC(56);
        if (mintClass == TYPE_C || mintClass == TYPE_B || mintClass == TYPE_P || mintClass == TYPE_M) {
            revert EC(65);
        }
        if (extension != address(0) && extension.code.length == 0) revert EC(66);
        typeToExtension[mintClass] = extension;
    }

    // ─── Creator Registry ─────────────────────────────────────────────────────

    /**
     * Register as a Creator (C), Brand (B), Proof Institution (P), or Museum (M).
     * One registration per wallet. Permanent.
     * Type prefix must be "C", "B", "P", or "M" — enforced by contract.
     * The 12-digit number is randomly generated — cannot be chosen.
     *
     * Cost: network gas only (no protocol fee).
     */
    function registerCreator(bytes1 typePrefix)
        external
        notFrozen
        returns (string memory creatorId)
    {
        if (!(_isValidType(typePrefix))) revert EC(54);
        if (!(bytes(_walletToCreatorId[msg.sender]).length == 0)) revert EC(53);

        uint64 number = _generateCreatorNumber();
        creatorId     = ODPPassportLib.buildCreatorId(typePrefix, number);

        _creators[creatorId] = CreatorRecord({
            creatorId:  creatorId,
            wallet:     msg.sender,
            typePrefix: typePrefix,
            timestamp:  block.timestamp
        });

        _walletToCreatorId[msg.sender] = creatorId;
        _creatorNumberTaken[number]    = true;

        emit CreatorRegistered(creatorId, msg.sender, typePrefix, block.timestamp);
        return creatorId;
    }

    function getCreator(string calldata creatorId)
        external view returns (CreatorRecord memory)
    {
        if (!(bytes(_creators[creatorId].creatorId).length > 0)) revert EC(2);
        return _creators[creatorId];
    }

    function getCreatorByWallet(address wallet)
        external view returns (string memory)
    {
        return _walletToCreatorId[wallet];
    }

    /**
     * Propose P-affiliation: caller (child P) requests linking to parent P.
     * One child P can have at most one active parent P.
     */
    function proposePAffiliation(string calldata parentPId)
        external
        notFrozen
    {
        string memory childPId = _requireRegistered();
        _requireTypeP(childPId);
        if (!(bytes(parentPId).length > 0)) revert EC(49);
        if (!(keccak256(bytes(parentPId)) != keccak256(bytes(childPId)))) revert EC(46);
        _requireTypeP(parentPId);
        if (!(bytes(_pParentOf[childPId]).length == 0)) revert EC(45);
        if (!(_pPendingParentsCountByChild[childPId] < MAX_P_PENDING_PARENTS_PER_CHILD)) revert EC(48);

        bytes32 k = keccak256(abi.encodePacked(parentPId, childPId));
        if (!(!_pendingPAffiliation[k])) revert EC(47);
        _pendingPAffiliation[k] = true;
        _pPendingParentsCountByChild[childPId] = _pPendingParentsCountByChild[childPId] + 1;

        emit PAffiliationProposed(parentPId, childPId, block.timestamp);
    }

    /**
     * Confirm P-affiliation: caller (parent P) confirms a pending child request.
     * Activates one-level link parent P -> child P.
     */
    function confirmPAffiliation(string calldata childPId)
        external
        notFrozen
    {
        string memory parentPId = _requireRegistered();
        _requireTypeP(parentPId);
        _requireTypeP(childPId);
        if (!(keccak256(bytes(parentPId)) != keccak256(bytes(childPId)))) revert EC(46);
        if (!(bytes(_pParentOf[childPId]).length == 0)) revert EC(45);

        bytes32 k = keccak256(abi.encodePacked(parentPId, childPId));
        if (!(_pendingPAffiliation[k])) revert EC(42);
        delete _pendingPAffiliation[k];
        _pPendingParentsCountByChild[childPId] = _pPendingParentsCountByChild[childPId] - 1;

        if (!(_pActiveChildrenCountByParent[parentPId] < MAX_P_ACTIVE_CHILDREN_PER_PARENT)) revert EC(44);

        _pParentOf[childPId] = parentPId;
        _pChildrenOf[parentPId].push(childPId);
        _pActiveChildrenCountByParent[parentPId] = _pActiveChildrenCountByParent[parentPId] + 1;

        _pAffiliationJoinedAt[childPId] = block.timestamp;
        delete _pAffiliationDetachedAt[childPId];
        delete _pLastDetachedParent[childPId];

        emit PAffiliationConfirmed(parentPId, childPId, block.timestamp);
    }

    /**
     * Parent P terminates an active affiliation (detach). Red-flag semantics for verifiers.
     * On-chain records detachedAt; active parent pointer is cleared (child may propose a new parent later).
     */
    function detachPAffiliation(string calldata childPId)
        external
        notFrozen
    {
        string memory parentPId = _requireRegistered();
        _requireTypeP(parentPId);
        _requireTypeP(childPId);
        if (!(keccak256(bytes(_pParentOf[childPId])) == keccak256(bytes(parentPId)))) revert EC(43);

        _removeChildFromParentList(parentPId, childPId);
        delete _pParentOf[childPId];
        _pActiveChildrenCountByParent[parentPId] = _pActiveChildrenCountByParent[parentPId] - 1;

        _pAffiliationDetachedAt[childPId] = block.timestamp;
        _pLastDetachedParent[childPId] = parentPId;

        emit PAffiliationDetached(parentPId, childPId, block.timestamp);
    }

    function _removeChildFromParentList(string memory parentPId, string memory childPId) internal {
        string[] storage ch = _pChildrenOf[parentPId];
        for (uint256 i = 0; i < ch.length; i++) {
            if (keccak256(bytes(ch[i])) == keccak256(bytes(childPId))) {
                ch[i] = ch[ch.length - 1];
                ch.pop();
                return;
            }
        }
        revert EC(63);
    }

    /**
     * Affiliation audit: active parent (if any), joinedAt from last confirmation, detachedAt if currently detached,
     * and last parent id recorded at detach (for history when active parent is empty).
     */
    function getPAffiliationAudit(string calldata childPId)
        external
        view
        returns (
            string memory activeParent,
            uint256 joinedAt,
            uint256 detachedAt,
            string memory lastDetachedFromParent
        )
    {
        activeParent = _pParentOf[childPId];
        joinedAt = _pAffiliationJoinedAt[childPId];
        detachedAt = _pAffiliationDetachedAt[childPId];
        lastDetachedFromParent = _pLastDetachedParent[childPId];
    }

    /**
     * Child can cancel its own pending request for a given parent.
     */
    function cancelPAffiliationRequest(string calldata parentPId)
        external
        notFrozen
    {
        string memory childPId = _requireRegistered();
        _requireTypeP(childPId);
        bytes32 k = keccak256(abi.encodePacked(parentPId, childPId));
        if (!(_pendingPAffiliation[k])) revert EC(42);
        delete _pendingPAffiliation[k];
        _pPendingParentsCountByChild[childPId] = _pPendingParentsCountByChild[childPId] - 1;
    }

    function isPAffiliationPending(string calldata parentPId, string calldata childPId)
        external
        view
        returns (bool)
    {
        return _pendingPAffiliation[keccak256(abi.encodePacked(parentPId, childPId))];
    }

    function getPAffiliatedParent(string calldata childPId)
        external
        view
        returns (string memory)
    {
        return _pParentOf[childPId];
    }

    function getPAffiliatedChildren(string calldata parentPId)
        external
        view
        returns (string[] memory)
    {
        return _pChildrenOf[parentPId];
    }

    function _stringArraySlice(string[] storage arr, uint256 offset, uint256 limit)
        internal
        view
        returns (string[] memory result, uint256 total)
    {
        total = arr.length;
        if (offset >= total) {
            return (new string[](0), total);
        }
        uint256 end = offset + limit;
        if (end > total) {
            end = total;
        }
        uint256 n = end - offset;
        result = new string[](n);
        for (uint256 i = 0; i < n; i++) {
            result[i] = arr[offset + i];
        }
    }

    /// @dev Paginated affiliated children for large parent lists (same slice semantics as `getPassportsByCreatorPaged`).
    function getPAffiliatedChildrenPaged(string calldata parentPId, uint256 offset, uint256 limit)
        external
        view
        returns (string[] memory result, uint256 total)
    {
        return _stringArraySlice(_pChildrenOf[parentPId], offset, limit);
    }

    // ─── Mint agent delegation (principal profile ↔ executing wallet) ───────────

    /**
     * Agent requests the right to mint passports for `principalCreatorId`.
     * The principal must call `confirmMintAgentRole(agent)` to activate.
     */
    function requestMintAgentRole(string calldata principalCreatorId) external notFrozen {
        if (!(bytes(principalCreatorId).length > 0)) revert EC(76);
        CreatorRecord storage cr = _creators[principalCreatorId];
        if (!(bytes(cr.creatorId).length > 0)) revert EC(2);
        if (!(msg.sender != cr.wallet)) revert EC(75);
        if (mintAgentForCreator[principalCreatorId] == msg.sender) {
            return;
        }
        bytes32 k = keccak256(abi.encodePacked(principalCreatorId, msg.sender));
        if (!(!mintAgentDelegationPending[k])) revert EC(74);
        mintAgentDelegationPending[k] = true;
        emit MintAgentUpdate(principalCreatorId, msg.sender, 0, block.timestamp);
    }

    /**
     * Principal (registered `msg.sender`) confirms a pending agent. Replaces any previous mint agent.
     */
    function confirmMintAgentRole(address agent) external notFrozen {
        if (!(agent != address(0))) revert EC(21);
        string memory artistCreatorId = _requireRegistered();
        bytes32 k = keccak256(abi.encodePacked(artistCreatorId, agent));
        if (!(mintAgentDelegationPending[k])) revert EC(73);
        delete mintAgentDelegationPending[k];
        address prev = mintAgentForCreator[artistCreatorId];
        mintAgentForCreator[artistCreatorId] = agent;
        if (prev != address(0) && prev != agent) {
            emit MintAgentUpdate(artistCreatorId, prev, 3, block.timestamp);
        }
        emit MintAgentUpdate(artistCreatorId, agent, 2, block.timestamp);
    }

    /// Principal revokes the active mint agent.
    function revokeMintAgentRole() external notFrozen {
        string memory artistCreatorId = _requireRegistered();
        address prev = mintAgentForCreator[artistCreatorId];
        if (!(prev != address(0))) revert EC(79);
        delete mintAgentForCreator[artistCreatorId];
        emit MintAgentUpdate(artistCreatorId, prev, 3, block.timestamp);
    }

    /// Active agent renounces the role for `principalCreatorId`.
    function renounceMintAgentRole(string calldata principalCreatorId) external notFrozen {
        if (!(bytes(principalCreatorId).length > 0)) revert EC(76);
        if (!(bytes(_creators[principalCreatorId].creatorId).length > 0)) revert EC(2);
        if (!(mintAgentForCreator[principalCreatorId] == msg.sender)) revert EC(72);
        delete mintAgentForCreator[principalCreatorId];
        emit MintAgentUpdate(principalCreatorId, msg.sender, 3, block.timestamp);
    }

    /// Agent cancels their own pending request before confirmation.
    function cancelMintAgentRequest(string calldata principalCreatorId) external notFrozen {
        if (!(bytes(principalCreatorId).length > 0)) revert EC(76);
        bytes32 k = keccak256(abi.encodePacked(principalCreatorId, msg.sender));
        if (!(mintAgentDelegationPending[k])) revert EC(73);
        delete mintAgentDelegationPending[k];
        emit MintAgentUpdate(principalCreatorId, msg.sender, 1, block.timestamp);
    }

    // ─── Passport Registry — Physical ─────────────────────────────────────────

    /// @dev Assumes `ODPPassportLib.validateDigitalMintInputs` already applied. Writes digital `Passport` and emits `PassportMinted`.
    /// @param principalWallet Issuer wallet on record (`Passport.creator` / initial `owner`).
    /// @param mintAgentForPassport `address(0)` if `msg.sender == principalWallet`; else executing delegate.
    function _mintDigitalCommit(
        string memory creatorId,
        DigitalMintInputs memory m,
        bool dataUrlIsFolderBase,
        address principalWallet,
        address mintAgentForPassport
    ) internal returns (string memory passportId) {
        passportId = _generatePassportId(m.year, m.month);
        string memory resolvedDataUrl = ODPPassportLib.resolveMintDataUrlMemory(m.dataUrl, dataUrlIsFolderBase, passportId);
        if (!(bytes(resolvedDataUrl).length <= 512)) revert EC(27);

        _passports[passportId] = Passport({
            passportId:         passportId,
            contractVersion: CONTRACT_VERSION,
            creator:         principalWallet,
            owner:           principalWallet,
            creatorId:       creatorId,
            year:            m.year,
            month:           m.month,
            objectType:      OBJECT_DIGITAL,
            dataHash:        m.dataHash,
            imageHash:       m.imageHash,
            imageHash2:      m.imageHash2,
            imageHash3:      m.imageHash3,
            fileHash:        m.fileHash,
            sealType:        0,
            sealHash:        bytes32(0),
            nfcPublicKey:    "",
            nfcModel:        "",
            dataUrl:         resolvedDataUrl,
            imageUrl:        m.imageUrl,
            imageUrl2:       m.imageUrl2,
            imageUrl3:       m.imageUrl3,
            timestamp:       block.timestamp,
            revoked:         false,
            revokedAt:       0,
            revocationReasonHash: bytes32(0),
            auxCommitmentHash: m.auxCommitmentHash,
            auxCommitmentUri:  m.auxCommitmentUri,
            mintAgent:         mintAgentForPassport
        });

        _creatorPassports[principalWallet].push(passportId);

        emit PassportMinted(passportId, principalWallet, creatorId, OBJECT_DIGITAL,
                            m.year, m.month, m.dataHash, 0, "", block.timestamp, mintAgentForPassport);
    }

    /// @dev After `ODPPassportLib` physical + aux validation.
    function _mintPhysicalCommit(
        string memory creatorId,
        PhysicalMintInputs memory m,
        bool dataUrlIsFolderBase,
        address principalWallet,
        address mintAgentForPassport
    ) internal returns (string memory passportId) {
        passportId = _generatePassportId(m.year, m.month);
        string memory resolvedDataUrl = ODPPassportLib.resolveMintDataUrlMemory(m.dataUrl, dataUrlIsFolderBase, passportId);
        if (!(bytes(resolvedDataUrl).length <= 512)) revert EC(27);

        _passports[passportId] = Passport({
            passportId:         passportId,
            contractVersion: CONTRACT_VERSION,
            creator:         principalWallet,
            owner:           principalWallet,
            creatorId:       creatorId,
            year:            m.year,
            month:           m.month,
            objectType:      OBJECT_PHYSICAL,
            dataHash:        m.dataHash,
            imageHash:       m.imageHash,
            imageHash2:      m.imageHash2,
            imageHash3:      m.imageHash3,
            fileHash:        bytes32(0),
            sealType:        m.sealType,
            sealHash:        m.sealHash,
            nfcPublicKey:    m.nfcPublicKey,
            nfcModel:        m.nfcModel,
            dataUrl:         resolvedDataUrl,
            imageUrl:        m.imageUrl,
            imageUrl2:       m.imageUrl2,
            imageUrl3:       m.imageUrl3,
            timestamp:       block.timestamp,
            revoked:         false,
            revokedAt:       0,
            revocationReasonHash: bytes32(0),
            auxCommitmentHash: m.auxCommitmentHash,
            auxCommitmentUri:  m.auxCommitmentUri,
            mintAgent:         mintAgentForPassport
        });

        _creatorPassports[principalWallet].push(passportId);

        emit PassportMinted(passportId, principalWallet, creatorId, OBJECT_PHYSICAL,
                            m.year, m.month, m.dataHash, m.sealType, m.nfcModel, block.timestamp, mintAgentForPassport);
    }

    /**
     * Register a PHYSICAL object.
     *
     * @param year          Must equal UTC calendar year of `block.timestamp` (ODP-ID `YYYY-MM` prefix).
     * @param month         Must equal UTC calendar month (1–12) of `block.timestamp`.
     */
    function mintPhysical(
        uint32  year,
        uint8   month,
        bytes32 dataHash,
        string  calldata dataUrl,
        bytes32 imageHash,
        string  calldata imageUrl,
        uint8   sealType,
        bytes32 sealHash,
        bytes   calldata nfcPublicKey,
        string  calldata nfcModel,
        bytes32 imageHash2,
        string  calldata imageUrl2,
        bytes32 imageHash3,
        string  calldata imageUrl3,
        bool dataUrlIsFolderBase,
        bytes32 auxCommitmentHash,
        string  calldata auxCommitmentUri,
        string  calldata mintOnBehalfOfCreatorId
    ) external notFrozen returns (string memory passportId) {
        (string memory creatorId, address principalWallet, address mintAgentAddr) = _beginMint(mintOnBehalfOfCreatorId);

        PhysicalMintInputs memory m = PhysicalMintInputs({
            year: year,
            month: month,
            dataHash: dataHash,
            dataUrl: dataUrl,
            imageHash: imageHash,
            imageUrl: imageUrl,
            sealType: sealType,
            sealHash: sealHash,
            nfcPublicKey: nfcPublicKey,
            nfcModel: nfcModel,
            imageHash2: imageHash2,
            imageUrl2: imageUrl2,
            imageHash3: imageHash3,
            imageUrl3: imageUrl3,
            auxCommitmentHash: auxCommitmentHash,
            auxCommitmentUri: auxCommitmentUri
        });
        ODPPassportLib.validatePhysicalMintForMint(m);
        _requireUtcYearMonth(year, month);
        return _mintPhysicalCommit(creatorId, m, dataUrlIsFolderBase, principalWallet, mintAgentAddr);
    }

    // ─── Passport Registry — Digital ──────────────────────────────────────────

    /**
     * Register a DIGITAL object.
     *
     * Caller must be registered (profile ID mandatory).
     * No seal required. fileHash is mandatory.
     *
     * @param year          Must equal UTC calendar year of `block.timestamp` (ODP-ID `YYYY-MM` prefix).
     * @param month         Must equal UTC calendar month (1–12) of `block.timestamp`.
     * @param dataHash      SHA-256 of minified passport.json
     * @param dataUrl       Public HTTPS URL of the §15 `.odpass` bundle (max 512 chars). May be "" — verifiers cannot fetch without a URL.
     * @param imageHash     SHA-256 of preview image. bytes32(0) = none
     * @param imageUrl      Preview image URL hint. "" = none
     * @param fileHash      SHA-256 of the original digital file. Required.
     * @param dataUrlIsFolderBase If true, `dataUrl` is folder root only; stored URL is `folderBase/passportId.odpass` (§15 bundle).
     * @param auxCommitmentHash Optional second document commitment (0 with empty URI if unused).
     * @param auxCommitmentUri Optional HTTPS hint for that document (max 512 chars if hash set).
     * @param mintOnBehalfOfCreatorId Pass "" to mint as the registered caller. Otherwise the principal profile id
     *        the caller mints for — `msg.sender` must be the active mint agent for that id (see `requestMintAgentRole` / `confirmMintAgentRole`).
     */
    function mintDigital(
        uint32  year,
        uint8   month,
        bytes32 dataHash,
        string  calldata dataUrl,
        bytes32 imageHash,
        string  calldata imageUrl,
        bytes32 imageHash2,
        string  calldata imageUrl2,
        bytes32 imageHash3,
        string  calldata imageUrl3,
        bytes32 fileHash,
        bool dataUrlIsFolderBase,
        bytes32 auxCommitmentHash,
        string  calldata auxCommitmentUri,
        string  calldata mintOnBehalfOfCreatorId
    ) external notFrozen returns (string memory passportId) {
        (string memory creatorId, address principalWallet, address mintAgentAddr) = _beginMint(mintOnBehalfOfCreatorId);
        DigitalMintInputs memory dm = DigitalMintInputs({
            year: year,
            month: month,
            dataHash: dataHash,
            dataUrl: dataUrl,
            imageHash: imageHash,
            imageUrl: imageUrl,
            imageHash2: imageHash2,
            imageUrl2: imageUrl2,
            imageHash3: imageHash3,
            imageUrl3: imageUrl3,
            fileHash: fileHash,
            auxCommitmentHash: auxCommitmentHash,
            auxCommitmentUri: auxCommitmentUri
        });
        ODPPassportLib.validateDigitalMintInputs(dm);
        _requireUtcYearMonth(year, month);
        return _mintDigitalCommit(creatorId, dm, dataUrlIsFolderBase, principalWallet, mintAgentAddr);
    }

    /**
     * @notice DIGITAL mint where `payload` is validated/normalized by a governance-registered `IODPExtension`.
     * @param mintClass Route byte (not C/B/P/M). Must have `typeToExtension[mintClass] != address(0)`.
     * @param payload Opaque input forwarded to the extension.
     * @dev Extension `normalize` **must** return `abi.encode` of the **13-tuple** (digital + aux):
     *      `(year,month,dataHash,dataUrl,imageHash,imageUrl,imageHash2,imageUrl2,imageHash3,imageUrl3,fileHash,auxCommitmentHash,auxCommitmentUri)`.
     */
    function mintDigitalViaExtension(
        bytes1 mintClass,
        bytes calldata payload,
        bool dataUrlIsFolderBase,
        string calldata mintOnBehalfOfCreatorId
    ) external notFrozen returns (string memory passportId) {
        address ext = typeToExtension[mintClass];
        if (!(ext != address(0))) revert EC(64);

        (string memory creatorId, address principalWallet, address mintAgentAddr) = _beginMint(mintOnBehalfOfCreatorId);

        IODPExtension(ext).validate(payload);
        bytes memory norm = IODPExtension(ext).normalize(payload);

        DigitalMintInputs memory dm = ODPPassportLib.decodeAndValidateDigitalExtensionNorm(norm);
        _requireUtcYearMonth(dm.year, dm.month);
        passportId = _mintDigitalCommit(creatorId, dm, dataUrlIsFolderBase, principalWallet, mintAgentAddr);
        emit ExtensionMintUsed(mintClass, EXT_MINT_KIND_DIGITAL, passportId);
    }

    /**
     * @notice PHYSICAL mint via `IODPExtension`. Same `mintClass` registry as digital; decode shape differs.
     * @dev `normalize` **must** return `abi.encode` of:
     *      `(year,month,dataHash,dataUrl,imageHash,imageUrl,sealType,sealHash,nfcPublicKey,nfcModel,imageHash2,imageUrl2,imageHash3,imageUrl3,auxCommitmentHash,auxCommitmentUri)`.
     */
    function mintPhysicalViaExtension(
        bytes1 mintClass,
        bytes calldata payload,
        bool dataUrlIsFolderBase,
        string calldata mintOnBehalfOfCreatorId
    ) external notFrozen returns (string memory passportId) {
        address ext = typeToExtension[mintClass];
        if (!(ext != address(0))) revert EC(64);

        (string memory creatorId, address principalWallet, address mintAgentAddr) = _beginMint(mintOnBehalfOfCreatorId);

        IODPExtension(ext).validate(payload);
        bytes memory norm = IODPExtension(ext).normalize(payload);

        PhysicalMintInputs memory pm = ODPPassportLib.decodeAndValidatePhysicalExtensionNorm(norm);
        _requireUtcYearMonth(pm.year, pm.month);

        passportId = _mintPhysicalCommit(creatorId, pm, dataUrlIsFolderBase, principalWallet, mintAgentAddr);
        emit ExtensionMintUsed(mintClass, EXT_MINT_KIND_PHYSICAL, passportId);
    }

    // ─── Passport — Update ────────────────────────────────────────────────────

    function _canUpdatePassportUrls(Passport storage p) internal view returns (bool) {
        if (msg.sender == p.creator || msg.sender == p.owner) return true;
        DelegationInfo storage d = _creatorPublishDelegation[p.creator];
        return d.agent == msg.sender && d.expiresAt > block.timestamp;
    }

    /// Registered creator (`msg.sender`) designates a single wallet that may update hosted URLs for **all** their passports.
    function delegateCreatorPublishing(address agent, uint256 expiresAt) external notFrozen {
        if (!(agent != address(0))) revert EC(21);
        _requireRegistered();
        if (!(expiresAt > block.timestamp)) revert EC(20);
        _creatorPublishDelegation[msg.sender] = DelegationInfo({ agent: agent, expiresAt: expiresAt });
        emit CreatorPublishingDelegated(msg.sender, agent, expiresAt);
    }

    function revokeCreatorPublishing() external notFrozen {
        _requireRegistered();
        delete _creatorPublishDelegation[msg.sender];
        emit CreatorPublishingDelegationRevoked(msg.sender, block.timestamp);
    }

    function getCreatorPublishingDelegation(address creatorWallet)
        external
        view
        returns (address agent, uint256 expiresAt)
    {
        DelegationInfo storage d = _creatorPublishDelegation[creatorWallet];
        return (d.agent, d.expiresAt);
    }

    /**
     * Update hosting URLs only — dataUrl and imageUrl.
     * Use this when moving the hosted `.odpass` bundle or image to a new host.
     *
     * ALL HASHES ARE IMMUTABLE after minting:
     *   dataHash, imageHash, fileHash, sealHash — cannot change ever.
     *
     * The caller must provide confirmedDataHash matching the on-chain dataHash.
     * This proves the caller knows the original content and prevents accidental
     * URL mistakes that would make the passport appear tampered.
     *
     * Note: this does NOT protect against a stolen wallet — dataHash is public
     * on-chain, so anyone with wallet access can read and pass it. This is a
     * UX safeguard, not a security mechanism.
     *
     * Authorized callers: passport **creator** or **owner**, or the **creator’s active publishing agent**
     * (`delegateCreatorPublishing` / `getCreatorPublishingDelegation`).
     *
     * Folder-base mint (`dataUrlIsFolderBase` on mint) only affects the **initial** stored URL.
     * This function always sets **literal** `newDataUrl` / `newImageUrl` (no folder resolution here).
     *
     * @param confirmedDataHash  Must equal the on-chain dataHash. Prevents
     *                           accidental URL updates pointing to wrong content.
     */
    function updatePassportUrls(
        string  calldata passportId,
        string  calldata newDataUrl,
        string  calldata newImageUrl,
        bytes32          confirmedDataHash
    ) external notFrozen {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!_canUpdatePassportUrls(p)) revert EC(26);
        if (!(p.dataHash == confirmedDataHash)) revert EC(25);
        if (!(bytes(newDataUrl).length <= 512)) revert EC(24);
        if (!(bytes(newImageUrl).length <= 512)) revert EC(23);

        // Only primary JSON + primary image URLs — hashes are immutable (extra image URLs unchanged here).
        p.dataUrl  = newDataUrl;
        p.imageUrl = newImageUrl;

        emit PassportUrlsUpdated(passportId, newDataUrl, newImageUrl);
    }

    /**
     * Update optional second commitment (e.g. COA PDF) and its URL hint. Does not change `dataHash` / image hashes.
     * @dev Only **creator** or **governance**. Revoked passports cannot be updated. `(bytes32(0), "")` clears the aux slot.
     */
    function updatePassportAuxCommitment(
        string calldata passportId,
        bytes32 newHash,
        string calldata newUri
    ) external notFrozen {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!(msg.sender == p.creator || msg.sender == governance)) revert EC(67);
        ODPPassportLib.validateAuxCommitmentFields(newHash, newUri);
        p.auxCommitmentHash = newHash;
        p.auxCommitmentUri = newUri;
        emit PassportAuxCommitmentUpdated(passportId, newHash, newUri, msg.sender, block.timestamp);
    }

    /// Current owner (starts as creator) may transfer the passport record to a new wallet.
    function transferPassport(string calldata passportId, address newOwner) external notFrozen {
        if (!(newOwner != address(0))) revert EC(22);
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!(p.owner == msg.sender)) revert EC(19);
        p.owner = newOwner;
        emit PassportTransferred(passportId, msg.sender, newOwner, block.timestamp);
    }

    /**
     * Irreversible passport revocation. Creator or governance may revoke.
     * reasonHash should be keccak256(utf8(reason)) for verifiers; full text may live off-chain.
     */
    function revokePassport(string calldata passportId, bytes32 reasonHash) external notFrozen {
        Passport storage p = _passports[passportId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(18);
        if (!(msg.sender == p.creator || msg.sender == governance)) revert EC(17);
        if (!(reasonHash != bytes32(0))) revert EC(16);
        p.revoked = true;
        p.revokedAt = block.timestamp;
        p.revocationReasonHash = reasonHash;
        emit PassportRevoked(passportId, msg.sender, reasonHash, block.timestamp);
    }

    // ─── Passport — Read ──────────────────────────────────────────────────────

    function getPassport(string calldata passportId)
        external view returns (Passport memory)
    {
        if (!(_passports[passportId].creator != address(0))) revert EC(12);
        return _passports[passportId];
    }

    function exists(string calldata passportId) external view returns (bool) {
        return _passports[passportId].creator != address(0);
    }

    function getPassportsByCreator(address creator)
        external view returns (string[] memory)
    {
        return _creatorPassports[creator];
    }

    function getPassportsByCreatorPaged(address creator, uint256 offset, uint256 limit)
        external
        view
        returns (string[] memory result, uint256 total)
    {
        return _stringArraySlice(_creatorPassports[creator], offset, limit);
    }

    // ─── Proof Registry ───────────────────────────────────────────────────────

    /**
     * Submit a Proof attestation for a registered passport.
     * Caller must be registered as type P (Proof Institution) or M (Museum).
     *
     * @param passportId   The passport being attested
     * @param noteHash  SHA-256 of attached document. bytes32(0) = none
     * @param noteUrl   URL of attached document. "" = none
     * @param year      Must equal UTC calendar year of `block.timestamp` (PRF-ID `YYYY-MM` prefix).
     * @param month     Must equal UTC calendar month (1–12) of `block.timestamp`.
     *
     * The exact block timestamp is always stored in `ProofRecord.timestamp` as well.
     */
    function submitProof(
        string  calldata passportId,
        bytes32          noteHash,
        string  calldata noteUrl,
        uint32           year,
        uint8            month
    ) external notFrozen returns (string memory proofId) {
        Passport storage pPass = _passports[passportId];
        if (!(pPass.creator != address(0))) revert EC(12);
        if (!(!pPass.revoked)) revert EC(11);
        if (!(bytes(noteUrl).length <= 512)) revert EC(10);
        if (!(year > 0)) revert EC(9);
        if (!(month >= 1 && month <= 12)) revert EC(8);
        _requireUtcYearMonth(year, month);

        string memory callerId = _walletToCreatorId[msg.sender];
        if (!(bytes(callerId).length > 0)) revert EC(7);
        bytes1 tp = _creators[callerId].typePrefix;
        if (!(tp == TYPE_P || tp == TYPE_M)) revert EC(6);

        if (noteHash == bytes32(0)) {
            if (!(bytes(noteUrl).length == 0)) revert EC(5);
        }

        proofId = _generateProofId(year, month, passportId);

        _proofs[proofId] = ProofRecord({
            proofId:         proofId,
            contractVersion: CONTRACT_VERSION,
            prover:          callerId,
            passportId:         passportId,
            noteHash:        noteHash,
            noteUrl:         noteUrl,
            timestamp:       block.timestamp
        });

        _passportProofs[passportId].push(proofId);
        _institutionProofs[callerId].push(proofId);

        emit ProofSubmitted(proofId, passportId, callerId, block.timestamp);
        return proofId;
    }

    function getProofsForPassport(string calldata passportId)
        external view returns (string[] memory)
    {
        return _passportProofs[passportId];
    }

    function getProof(string calldata proofId)
        external view returns (ProofRecord memory)
    {
        if (!(bytes(_proofs[proofId].proofId).length > 0)) revert EC(4);
        return _proofs[proofId];
    }

    function getProofsByInstitution(string calldata creatorId)
        external view returns (string[] memory)
    {
        return _institutionProofs[creatorId];
    }

    // ─── Internal: validation ─────────────────────────────────────────────────

    function _requireRegistered() internal view returns (string memory creatorId) {
        creatorId = _walletToCreatorId[msg.sender];
        if (!(bytes(creatorId).length > 0)) revert EC(3);
    }

    /**
     * @return creatorId Profile id written on the passport.
     * @return principalWallet Issuer wallet (`Passport.creator` / initial `owner`).
     * @return mintAgentAddr `address(0)` if principal mints; else `msg.sender` (delegate).
     */
    function _resolveMintPrincipal(string calldata mintOnBehalfOfCreatorId)
        internal
        view
        returns (string memory creatorId, address principalWallet, address mintAgentAddr)
    {
        if (bytes(mintOnBehalfOfCreatorId).length == 0) {
            creatorId = _walletToCreatorId[msg.sender];
            if (!(bytes(creatorId).length > 0)) revert EC(3);
            return (creatorId, msg.sender, address(0));
        }
        creatorId = mintOnBehalfOfCreatorId;
        CreatorRecord storage cr = _creators[creatorId];
        if (!(bytes(cr.creatorId).length > 0)) revert EC(2);
        principalWallet = cr.wallet;
        if (msg.sender == principalWallet) {
            return (creatorId, principalWallet, address(0));
        }
        if (!(mintAgentForCreator[creatorId] == msg.sender)) revert EC(72);
        return (creatorId, principalWallet, msg.sender);
    }

    /** Enforce registration (caller or agent path), monthly limit on **principal** wallet, increment counter. */
    function _beginMint(string calldata mintOnBehalfOfCreatorId)
        internal
        returns (string memory creatorId, address principalWallet, address mintAgentAddr)
    {
        (creatorId, principalWallet, mintAgentAddr) = _resolveMintPrincipal(mintOnBehalfOfCreatorId);
        _checkAndIncrementMintLimit(creatorId, principalWallet);
    }

    /// @dev `year`/`month` must match Gregorian UTC calendar of `block.timestamp` (ODP-ID prefix binds to mint month).
    function _requireUtcYearMonth(uint32 year, uint8 month) private view {
        (uint32 cy, uint8 cm) = ODPPassportLib.utcYearMonthFromTimestamp(block.timestamp);
        if (!(year == cy && month == cm)) revert EC(68);
    }

    function _isValidType(bytes1 t) internal pure returns (bool) {
        return t == TYPE_C || t == TYPE_B || t == TYPE_P || t == TYPE_M;
    }

    function _requireTypeP(string memory creatorId) internal view {
        CreatorRecord storage c = _creators[creatorId];
        if (!(bytes(c.creatorId).length > 0)) revert EC(2);
        if (!(c.typePrefix == TYPE_P)) revert EC(71);
    }

    /**
     * Check monthly mint limit and increment counter (C/B only; P and M are unlimited).
     * Counts against **principal** issuer wallet (so an agent consumes the artist’s tier quota).
     * Resets on calendar month boundary (yearMonth key changes).
     */
    function _checkAndIncrementMintLimit(string memory creatorId, address principalWallet) internal {
        bytes1 t = _creators[creatorId].typePrefix;
        if (t == TYPE_P || t == TYPE_M) {
            return;
        }
        uint32 limit = (t == TYPE_B) ? MONTHLY_LIMIT_B : MONTHLY_LIMIT_C;
        uint32 ym = _currentYearMonth();
        uint32 count = _mintCount[principalWallet][ym];
        if (!(count < limit)) revert EC(1);
        _mintCount[principalWallet][ym] = count + 1;
    }

    function _currentYearMonth() internal view returns (uint32) {
        uint32 year = _currentYear();
        uint8 month = _currentMonth();
        return year * 100 + uint32(month);
    }

    function _currentYear() internal view returns (uint32) {
        return uint32(1970 + block.timestamp / 31_556_952);
    }

    function _currentMonth() internal view returns (uint8) {
        uint256 secsInYear = block.timestamp % 31_556_952;
        uint256 m = secsInYear / 2_629_746 + 1;
        if (m > 12) m = 12;
        return uint8(m);
    }

    /**
     * Get remaining mints for a wallet in the current calendar month.
     * For P- and M-type creators, returns `type(uint32).max` (unlimited).
     */
    function getRemainingMints(address wallet) external view returns (uint32) {
        string memory cid = _walletToCreatorId[wallet];
        if (bytes(cid).length == 0) {
            return 0;
        }
        bytes1 t = _creators[cid].typePrefix;
        if (t == TYPE_P || t == TYPE_M) {
            return type(uint32).max;
        }
        uint32 limit = (t == TYPE_B) ? MONTHLY_LIMIT_B : MONTHLY_LIMIT_C;
        uint32 ym = _currentYearMonth();
        uint32 used = _mintCount[wallet][ym];
        if (used >= limit) return 0;
        return limit - used;
    }

    // ─── Internal: ID generation ──────────────────────────────────────────────

    /**
     * Generate a unique profile ID number (0–999,999,999,999).
     * Uses keccak256 entropy with nonce. Retries on collision (max 25 attempts).
     */
    function _generateCreatorNumber() internal returns (uint64) {
        uint256 baseNonce = _creatorNonce;
        for (uint i = 0; i < 25; i++) {
            // Combine multiple sources for better unpredictability.
            // Note: on-chain entropy is never truly random — IDs are not
            // security-critical (no funds at stake), so this is acceptable.
            uint64 n = uint64(uint256(keccak256(abi.encodePacked(
                block.timestamp,
                block.prevrandao,   // replaces block.difficulty post-Merge
                msg.sender,
                baseNonce + i,
                gasleft()
            ))) % 1_000_000_000_000);
            if (!_creatorNumberTaken[n]) {
                _creatorNonce = baseNonce + i + 1;
                return n;
            }
        }
        revert EC(62);
    }

    /**
     * Generate a unique Passport ID number (0–999,999,999) for year+month.
     * Uses keccak256 entropy with nonce. Retries on collision (max 25 attempts).
     */
    function _generatePassportId(uint32 year, uint8 month)
        internal returns (string memory)
    {
        uint32 key = uint32(year) * 100 + uint32(month);
        uint256 baseNonce = _passportNonce;
        for (uint i = 0; i < 25; i++) {
            uint32 n = uint32(uint256(keccak256(abi.encodePacked(
                block.timestamp,
                block.prevrandao,
                msg.sender,
                baseNonce + i,
                key,
                gasleft()
            ))) % 1_000_000_000);
            if (!_passportNumberTaken[key][n]) {
                _passportNonce = baseNonce + i + 1;
                _passportNumberTaken[key][n] = true;
                return ODPPassportLib.formatOdpPassportId(year, month, n);
            }
        }
        revert EC(61);
    }

    /**
     * Generate a unique Proof ID number (0–99,999,999) for year+month.
     */
    function _generateProofId(uint32 year, uint8 month, string memory passportId)
        internal returns (string memory)
    {
        uint32 key = uint32(year) * 100 + uint32(month);
        uint256 baseNonce = _proofNonce;
        bytes32 passportIdHash = keccak256(bytes(passportId));
        for (uint i = 0; i < 25; i++) {
            uint32 n = uint32(uint256(keccak256(abi.encodePacked(
                block.timestamp,
                block.prevrandao,
                msg.sender,
                baseNonce + i,
                key,
                passportIdHash,
                gasleft()
            ))) % 100_000_000);
            if (!_proofNumberTaken[key][n]) {
                _proofNonce = baseNonce + i + 1;
                _proofNumberTaken[key][n] = true;
                return ODPPassportLib.formatPrfId(year, month, n);
            }
        }
        revert EC(60);
    }

    // Approximate calendar from block.timestamp: rate-limit buckets only (±1 month drift acceptable).

}
