// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * Object Digital Passport — Smart Contract
 * @author Andrei Chernikov
 * Specification v0.3
 * License: MIT
 *
 * Deployed on: Polygon PoS (chain ID 137)
 * Testnet:     Polygon Amoy (chain ID 80002)
 *
 * Three registries in one contract:
 *   1. Creator Registry  — C / B / P / M identifiers
 *   2. Passport Registry — physical and digital object records
 *   3. Proof Registry    — institution attestations
 *
 * All IDs are randomly generated by the contract.
 * A registered profile ID (`creatorId`) is mandatory for minting and proof submission.
 *
 * IMMUTABILITY:
 *   This contract is not upgradeable by design.
 *   No owner. No admin. No pause function. No selfdestruct.
 *   Rules cannot change after deployment.
 *   Protocol updates require a new contract (v0.2, v0.3, etc.).
 *   v0.3 adds: owner/transfer, account-scoped publishing agent for hosted URLs, revocation,
 *   extra image hashes, P-affiliation detach + timestamps, P/M counterfeit concern flag,
 *   governance (revocation). Type-definition governance is off-chain / SPEC (saves bytecode).
 *
 * SECURITY NOTES:
 *   - v0.2+: no protocol fee — native token only pays network gas (no POL routed to fee burn)
 *   - No external calls — reentrancy not possible
 *   - Solidity 0.8.20 — overflow/underflow protection built in
 *   - Access control enforced via require() on all write functions
 *   - On-chain randomness (block.prevrandao + gasleft) is not
 *     cryptographically secure but is acceptable here since IDs
 *     carry no financial value — only human-readability
 *   - NFC: only NTAG424DNA_TT accepted — standard chip can be reattached
 *   - Proof institutions (P) and museums (M) are open registration — verifiers must warn
 *     users to confirm P/M-type IDs on official institution websites
 *   - Creator is trusted to physically install the correct chip model
 *     The contract cannot verify hardware — only the declared model
 *   - Anti-spam: monthly mint-rate limit (no protocol fee — gas only)
 *   - Rate limit (per wallet, per calendar month): C = 1000, B = 100_000, P/M = unlimited
 *   - Passport namespace: 100M IDs per year+month (previously 10M)
 *   - P-type whitelist is intentionally off-chain — see external repos
 *
 * SOURCE CODE:
 *   Published at: https://github.com/object-digital-passport/object-digital-passport
 *   Anyone can read, verify, fork, or deploy their own instance.
 */
/**
 * IODPExtension — interface for future extension contracts.
 *
 * Extensions validate and interpret type-specific data before core stores it.
 * v1 will route mint calls through registered extensions.
 * In v0 this interface is defined for forward compatibility — no extensions are active.
 *
 * Write flow (v1):
 *   User calls mintPassport(type, data)
 *   → Core looks up: extension = typeToExtension[type]
 *   → extension.validate(data)
 *   → extension.normalize(data) → canonical bytes
 *   → Core stores record and assigns ID
 *
 * Extensions can add new types (e.g. "V" for video, "G" for game items)
 * but only through a new contract version — not open registration.
 */
interface IODPExtension {
    /// Validate type-specific data. Reverts if invalid.
    function validate(bytes calldata data) external view;
    /// Normalize data to canonical form for storage.
    function normalize(bytes calldata data) external view returns (bytes memory);
}

contract ObjectDigitalPassport {

    error EC(uint16 code);

    // ─── Constants ────────────────────────────────────────────────────────────

    bytes1 constant TYPE_C = "C";
    bytes1 constant TYPE_B = "B";
    bytes1 constant TYPE_P = "P";
    bytes1 constant TYPE_M = "M";

    string constant OBJECT_PHYSICAL = "physical";
    string constant OBJECT_DIGITAL  = "digital";
    bytes32 constant NFC_NTAG424DNA_TT_HASH = keccak256("NTAG424DNA_TT");

    // On-chain spec line (variant: two uint8s, human-readable as major.minor).
    uint8 public constant SPEC_MAJOR = 0;
    uint8 public constant SPEC_MINOR = 3;

    /// Packed byte stored in Passport.contractVersion: `SPEC_MAJOR * 16 + SPEC_MINOR` (each must stay < 16).
    /// Spec line **0.3** → packed **3**: ownership/revocation/images/P-affiliation/counterfeit/governance, plus
    /// **account-scoped publishing agent** for `updatePassportUrls`.
    uint8 public constant CONTRACT_VERSION = SPEC_MAJOR * 16 + SPEC_MINOR;

    // Anti-spam: per-wallet, per-calendar-month mint caps (no protocol fee). Tier follows profile ID prefix (C/B/P/M).
    uint32 public constant MONTHLY_LIMIT_C = 1000;
    uint32 public constant MONTHLY_LIMIT_B = 100_000;

    // ─── Structs ──────────────────────────────────────────────────────────────

    struct CreatorRecord {
        string  creatorId;    // "C-482-930-174-005"
        address wallet;
        bytes1  typePrefix;   // "C", "B", "P", or "M" — stored as bytes1 for gas efficiency
        uint256 timestamp;
    }

    struct Passport {
        string  humanId;       // Passport ID (SPEC); ODP-… string; ABI name humanId
        uint8   contractVersion; // packed SPEC_MAJOR/SPEC_MINOR (see CONTRACT_VERSION) at mint
        address creator;       // immutable issuer wallet at mint
        address owner;         // current holder; starts as creator; changes via transferPassport
        string  creatorId;     // Profile ID (SPEC); mandatory
        uint32  year;          // uint32 supports any year from 1 to 4,294,967,295
        uint8   month;
        string  objectType;    // "physical" or "digital"
        bytes32 dataHash;      // SHA-256 of minified passport.json
        bytes32 imageHash;     // SHA-256 of primary image. bytes32(0) = none
        bytes32 imageHash2;    // optional 2nd image (max 3 on-chain hashes total)
        bytes32 imageHash3;    // optional 3rd image
        bytes32 fileHash;      // SHA-256 of digital file. bytes32(0) if physical
        uint8   sealType;      // 1=NFC, 2=numbered, 3=both. 0 if digital
        bytes32 sealHash;      // SHA-256 of seal object. bytes32(0) if digital
        bytes   nfcPublicKey;  // NFC chip public key. empty if no NFC seal
        string  nfcModel;      // "NTAG424DNA_TT" if NFC. empty if no NFC seal
        string  dataUrl;
        string  imageUrl;
        string  imageUrl2;     // optional URL hints for extra images
        string  imageUrl3;
        uint256 timestamp;
        bool    revoked;       // passport revoked (creator or governance)
        uint256 revokedAt;
        bytes32 revocationReasonHash; // keccak256 of UTF-8 reason; 0 if not revoked
    }

    struct ProofRecord {
        string  proofId;         // "PRF-2031-03-7392018"
        uint8   contractVersion; // packed SPEC_MAJOR/SPEC_MINOR at submission
        string  prover;          // Profile ID of P- or M-type institution
        string  humanId;         // attested passport
        bytes32 noteHash;        // SHA-256 of attached document. bytes32(0) = none
        string  noteUrl;
        uint256 timestamp;
    }

    /// Off-chain document (e.g. PDF contract): creator anchors SHA-256 on-chain — verifiers compare file bytes.
    struct ExternalDocAttestation {
        address creator;
        string  creatorId;
        bytes32 documentHash;
        uint256 timestamp;
        string  documentUri; // optional HTTPS link to the same file; max 512 chars
    }

    // ─── Storage ──────────────────────────────────────────────────────────────

    // Creator Registry
    mapping(string  => CreatorRecord) private _creators;
    mapping(address => string)        private _walletToCreatorId;
    mapping(uint64  => bool)          private _creatorNumberTaken;
    uint256 private _creatorNonce;

    // Passport Registry
    // key = year * 100 + month → set of random numbers taken
    mapping(uint32 => mapping(uint32 => bool)) private _passportNumberTaken;
    mapping(string => Passport)   private _passports;
    mapping(address => string[])  private _creatorPassports;
    uint256 private _passportNonce;

    // Proof Registry
    mapping(uint32 => mapping(uint32 => bool)) private _proofNumberTaken;
    mapping(string => ProofRecord)  private _proofs;
    mapping(string => string[])     private _passportProofs;
    mapping(string => string[])     private _institutionProofs;
    uint256 private _proofNonce;

    // Rate limiting — mints per wallet per calendar month (C/B tiers; P skips limit)
    // key = address → (yearMonth uint32 e.g. 202603) → count
    mapping(address => mapping(uint32 => uint32)) private _mintCount;

    // External document attestations — key = keccak256(abi.encodePacked(wallet, documentHash))
    mapping(bytes32 => ExternalDocAttestation) private _externalDocAttest;

    // P-affiliation (one-level): child P -> exactly one parent P.
    // Handshake is two-step to reduce spam:
    // 1) child proposes parent, 2) parent confirms.
    mapping(bytes32 => bool)      private _pendingPAffiliation; // key = keccak256(parentId, childId)
    mapping(string  => string)    private _pParentOf;           // childPId -> parentPId (active)
    mapping(string  => string[])  private _pChildrenOf;         // parentPId -> childPId[]

    // Hard caps (v0.2 anti-growth limits)
    uint16 private constant MAX_P_ACTIVE_CHILDREN_PER_PARENT = 100;
    uint16 private constant MAX_P_PENDING_PARENTS_PER_CHILD  = 100;
    mapping(string => uint16) private _pActiveChildrenCountByParent; // parentPId -> active children count
    mapping(string => uint16) private _pPendingParentsCountByChild;   // childPId -> pending parent requests count

    /// When affiliation became active (parent confirmed). 0 if never linked.
    mapping(string => uint256) private _pAffiliationJoinedAt;
    /// Non-zero after detach while child has no active parent (cleared on new confirm).
    mapping(string => uint256) private _pAffiliationDetachedAt;
    /// Parent P id at time of last detach (for verifier audit when active parent is empty).
    mapping(string => string)  private _pLastDetachedParent;

    struct DelegationInfo {
        address agent;
        uint256 expiresAt;
    }

    /// One optional publishing agent per **registered creator wallet** (the issuer account). When active, that
    /// agent may call `updatePassportUrls` for any passport with `p.creator == creatorWallet` (hash check unchanged).
    mapping(address => DelegationInfo) private _creatorPublishDelegation;

    /// Latest counterfeit / authenticity concern raised by P or M (prover is institution profile id).
    mapping(string => bool)    private _counterfeitActive;
    mapping(string => string)  private _counterfeitProverId;
    mapping(string => bytes32) private _counterfeitReasonHash;
    mapping(string => uint256) private _counterfeitTimestamp;

    /// Governance address (multisig / DAO): may revoke passports alongside creator.
    /// Type-definition governance is documented in SPEC; on-chain timelock registry was omitted for bytecode size.
    address public governance;

    // ── Extension Registry (v1 architecture) ─────────────────────────────────
    // Maps type bytes1 → extension contract address.
    // In v0 this is empty — all types are handled natively.
    // In v1 new types (e.g. "V", "G") can be added by deploying a new contract.
    // Adding extensions in v1 requires deployer governance (not open registration).
    mapping(bytes1 => address) public typeToExtension;

    // ── Freeze (for v0 → v1 migration) ─────────────────────────────────────────────
    // When v1 is ready, this contract can be frozen to stop new writes.
    // Frozen = historical archive. All existing records remain readable forever.
    // Only the deployer address can freeze. Cannot be unfrozen.
    address public immutable deployer;
    bool    public frozen;

    modifier notFrozen() {
        if (!(!frozen)) revert EC(59);
        _;
    }

    // ─── Events ───────────────────────────────────────────────────────────────

    event CreatorRegistered(
        string  indexed creatorId,
        address indexed wallet,
        bytes1          typePrefix,
        uint256         timestamp
    );

    event PassportMinted(
        string  indexed humanId,
        address indexed creator,
        string          creatorId,
        string          objectType,
        uint32          year,
        uint8           month,
        bytes32         dataHash,
        uint8           sealType,   // 0=digital, 1=NFC, 2=numbered, 3=both
        string          nfcModel,   // "NTAG424DNA_TT" or "" if no NFC
        uint256         timestamp
    );

    event PassportUrlsUpdated(
        string indexed humanId,
        string         newDataUrl,
        string         newImageUrl
    );

    event ProofSubmitted(
        string  indexed proofId,
        string  indexed humanId,
        string  indexed prover,
        uint256         timestamp
    );

    event ContractFrozen(uint256 timestamp);

    event ExternalDocumentAttested(
        string  indexed creatorId,
        address indexed creator,
        bytes32         documentHash,
        string          documentUri,
        uint256         timestamp
    );

    event PAffiliationProposed(
        string indexed parentPId,
        string indexed childPId,
        uint256 timestamp
    );

    event PAffiliationConfirmed(
        string indexed parentPId,
        string indexed childPId,
        uint256 timestamp
    );

    event PAffiliationDetached(
        string indexed parentPId,
        string indexed childPId,
        uint256 timestamp
    );

    event PassportTransferred(
        string  indexed humanId,
        address indexed from,
        address indexed to,
        uint256 timestamp
    );

    event CreatorPublishingDelegated(address indexed creator, address indexed agent, uint256 expiresAt);

    event CreatorPublishingDelegationRevoked(address indexed creator, uint256 timestamp);

    event PassportRevoked(
        string  indexed humanId,
        address indexed revokedBy,
        bytes32 reasonHash,
        uint256 timestamp
    );

    event CounterfeitConcernRaised(
        string indexed humanId,
        string indexed proverCreatorId,
        bytes32 reasonHash,
        uint256 timestamp
    );

    event CounterfeitConcernCleared(
        string indexed humanId,
        string indexed proverCreatorId,
        uint256 timestamp
    );

    event GovernanceTransferred(address indexed previous, address indexed next, uint256 timestamp);

    // ─── Constructor ──────────────────────────────────────────────────────────

    constructor() {
        deployer = msg.sender;
        governance = msg.sender;
    }

    // ─── Freeze ───────────────────────────────────────────────────────────────

    /**
     * Freeze this contract — no new records can be created after this.
     * Existing data remains readable forever.
     * Called once before deploying v1 to "seal" the v0.x registry.
     * Only the original deployer can freeze.
     */
    function freeze() external {
        if (!(msg.sender == deployer)) revert EC(58);
        if (!(!frozen)) revert EC(57);
        frozen = true;
        emit ContractFrozen(block.timestamp);
    }

    /// Governance may be a multisig or DAO-controlled address off-chain.
    function transferGovernance(address newGovernance) external {
        if (!(msg.sender == governance)) revert EC(56);
        if (!(newGovernance != address(0))) revert EC(55);
        address prev = governance;
        governance = newGovernance;
        emit GovernanceTransferred(prev, newGovernance, block.timestamp);
    }

    // ─── Creator Registry ─────────────────────────────────────────────────────

    /**
     * Register as a Creator (C), Brand (B), Proof Institution (P), or Museum (M).
     * One registration per wallet. Permanent.
     * Type prefix must be "C", "B", "P", or "M" — enforced by contract.
     * The 12-digit number is randomly generated — cannot be chosen.
     *
     * Cost: network gas only (no protocol fee).
     */
    function registerCreator(bytes1 typePrefix)
        external
        notFrozen
        returns (string memory creatorId)
    {
        if (!(_isValidType(typePrefix))) revert EC(54);
        if (!(bytes(_walletToCreatorId[msg.sender]).length == 0)) revert EC(53);

        uint64 number = _generateCreatorNumber();
        creatorId     = _buildCreatorId(typePrefix, number);

        _creators[creatorId] = CreatorRecord({
            creatorId:  creatorId,
            wallet:     msg.sender,
            typePrefix: typePrefix,
            timestamp:  block.timestamp
        });

        _walletToCreatorId[msg.sender] = creatorId;
        _creatorNumberTaken[number]    = true;

        emit CreatorRegistered(creatorId, msg.sender, typePrefix, block.timestamp);
        return creatorId;
    }

    function getCreator(string calldata creatorId)
        external view returns (CreatorRecord memory)
    {
        if (!(bytes(_creators[creatorId].creatorId).length > 0)) revert EC(2);
        return _creators[creatorId];
    }

    function getCreatorByWallet(address wallet)
        external view returns (string memory)
    {
        return _walletToCreatorId[wallet];
    }

    /**
     * Anchor SHA-256 of an off-chain document (e.g. PDF) for the caller's profile ID.
     * At most one attestation per (wallet, documentHash). Verifiers re-hash the file and compare.
     * Does not prove legal validity — only that this wallet recorded this hash on-chain.
     *
     * @param documentHash SHA-256 of raw file bytes (same encoding as passport fileHash).
     * @param documentUri  Optional HTTPS URL where the same file is hosted; may be "".
     */
    function attestExternalDocument(bytes32 documentHash, string calldata documentUri)
        external
        notFrozen
    {
        if (!(documentHash != bytes32(0))) revert EC(52);
        if (!(bytes(documentUri).length <= 512)) revert EC(51);
        string memory creatorId = _requireRegistered();
        bytes32 key = keccak256(abi.encodePacked(msg.sender, documentHash));
        if (!(_externalDocAttest[key].creator == address(0))) revert EC(50);

        _externalDocAttest[key] = ExternalDocAttestation({
            creator:      msg.sender,
            creatorId:    creatorId,
            documentHash: documentHash,
            timestamp:    block.timestamp,
            documentUri:  documentUri
        });

        emit ExternalDocumentAttested(creatorId, msg.sender, documentHash, documentUri, block.timestamp);
    }

    /**
     * Check whether a wallet attested a document hash and return metadata.
     */
    function getExternalDocumentAttestation(address wallet, bytes32 documentHash)
        external
        view
        returns (
            bool attested,
            string memory creatorId,
            uint256 timestamp,
            string memory documentUri
        )
    {
        bytes32 key = keccak256(abi.encodePacked(wallet, documentHash));
        ExternalDocAttestation storage a = _externalDocAttest[key];
        if (a.creator == address(0)) {
            return (false, "", 0, "");
        }
        return (true, a.creatorId, a.timestamp, a.documentUri);
    }

    /**
     * Propose P-affiliation: caller (child P) requests linking to parent P.
     * One child P can have at most one active parent P.
     */
    function proposePAffiliation(string calldata parentPId)
        external
        notFrozen
    {
        string memory childPId = _requireRegistered();
        _requireTypeP(childPId, "Only P-type child can propose affiliation");
        if (!(bytes(parentPId).length > 0)) revert EC(49);
        if (!(keccak256(bytes(parentPId)) != keccak256(bytes(childPId)))) revert EC(46);
        _requireTypeP(parentPId, "Parent must be P-type");
        if (!(bytes(_pParentOf[childPId]).length == 0)) revert EC(45);
        if (!(_pPendingParentsCountByChild[childPId] < MAX_P_PENDING_PARENTS_PER_CHILD)) revert EC(48);

        bytes32 k = keccak256(abi.encodePacked(parentPId, childPId));
        if (!(!_pendingPAffiliation[k])) revert EC(47);
        _pendingPAffiliation[k] = true;
        _pPendingParentsCountByChild[childPId] = _pPendingParentsCountByChild[childPId] + 1;

        emit PAffiliationProposed(parentPId, childPId, block.timestamp);
    }

    /**
     * Confirm P-affiliation: caller (parent P) confirms a pending child request.
     * Activates one-level link parent P -> child P.
     */
    function confirmPAffiliation(string calldata childPId)
        external
        notFrozen
    {
        string memory parentPId = _requireRegistered();
        _requireTypeP(parentPId, "Only P-type parent can confirm affiliation");
        _requireTypeP(childPId, "Child must be P-type");
        if (!(keccak256(bytes(parentPId)) != keccak256(bytes(childPId)))) revert EC(46);
        if (!(bytes(_pParentOf[childPId]).length == 0)) revert EC(45);

        bytes32 k = keccak256(abi.encodePacked(parentPId, childPId));
        if (!(_pendingPAffiliation[k])) revert EC(42);
        delete _pendingPAffiliation[k];
        _pPendingParentsCountByChild[childPId] = _pPendingParentsCountByChild[childPId] - 1;

        if (!(_pActiveChildrenCountByParent[parentPId] < MAX_P_ACTIVE_CHILDREN_PER_PARENT)) revert EC(44);

        _pParentOf[childPId] = parentPId;
        _pChildrenOf[parentPId].push(childPId);
        _pActiveChildrenCountByParent[parentPId] = _pActiveChildrenCountByParent[parentPId] + 1;

        _pAffiliationJoinedAt[childPId] = block.timestamp;
        delete _pAffiliationDetachedAt[childPId];
        delete _pLastDetachedParent[childPId];

        emit PAffiliationConfirmed(parentPId, childPId, block.timestamp);
    }

    /**
     * Parent P terminates an active affiliation (detach). Red-flag semantics for verifiers.
     * On-chain records detachedAt; active parent pointer is cleared (child may propose a new parent later).
     */
    function detachPAffiliation(string calldata childPId)
        external
        notFrozen
    {
        string memory parentPId = _requireRegistered();
        _requireTypeP(parentPId, "Only P-type parent can detach");
        _requireTypeP(childPId, "Child must be P-type");
        if (!(keccak256(bytes(_pParentOf[childPId])) == keccak256(bytes(parentPId)))) revert EC(43);

        _removeChildFromParentList(parentPId, childPId);
        delete _pParentOf[childPId];
        _pActiveChildrenCountByParent[parentPId] = _pActiveChildrenCountByParent[parentPId] - 1;

        _pAffiliationDetachedAt[childPId] = block.timestamp;
        _pLastDetachedParent[childPId] = parentPId;

        emit PAffiliationDetached(parentPId, childPId, block.timestamp);
    }

    function _removeChildFromParentList(string memory parentPId, string memory childPId) internal {
        string[] storage ch = _pChildrenOf[parentPId];
        for (uint256 i = 0; i < ch.length; i++) {
            if (keccak256(bytes(ch[i])) == keccak256(bytes(childPId))) {
                ch[i] = ch[ch.length - 1];
                ch.pop();
                return;
            }
        }
        revert EC(63);
    }

    /**
     * Affiliation audit: active parent (if any), joinedAt from last confirmation, detachedAt if currently detached,
     * and last parent id recorded at detach (for history when active parent is empty).
     */
    function getPAffiliationAudit(string calldata childPId)
        external
        view
        returns (
            string memory activeParent,
            uint256 joinedAt,
            uint256 detachedAt,
            string memory lastDetachedFromParent
        )
    {
        activeParent = _pParentOf[childPId];
        joinedAt = _pAffiliationJoinedAt[childPId];
        detachedAt = _pAffiliationDetachedAt[childPId];
        lastDetachedFromParent = _pLastDetachedParent[childPId];
    }

    /**
     * Child can cancel its own pending request for a given parent.
     */
    function cancelPAffiliationRequest(string calldata parentPId)
        external
        notFrozen
    {
        string memory childPId = _requireRegistered();
        _requireTypeP(childPId, "Only P-type child can cancel affiliation request");
        bytes32 k = keccak256(abi.encodePacked(parentPId, childPId));
        if (!(_pendingPAffiliation[k])) revert EC(42);
        delete _pendingPAffiliation[k];
        _pPendingParentsCountByChild[childPId] = _pPendingParentsCountByChild[childPId] - 1;
    }

    function isPAffiliationPending(string calldata parentPId, string calldata childPId)
        external
        view
        returns (bool)
    {
        return _pendingPAffiliation[keccak256(abi.encodePacked(parentPId, childPId))];
    }

    function getPAffiliatedParent(string calldata childPId)
        external
        view
        returns (string memory)
    {
        return _pParentOf[childPId];
    }

    function getPAffiliatedChildren(string calldata parentPId)
        external
        view
        returns (string[] memory)
    {
        return _pChildrenOf[parentPId];
    }

    /**
     * Paginated affiliated children (v0.2 standard-friendly read endpoint).
     * For large lists, frontends MUST use this method to avoid heavy responses.
     *
     * @return result children slice in range [offset, min(offset+limit, total))
     * @return total total count of active affiliated children for parentPId
     */
    function getPAffiliatedChildrenPaged(
        string calldata parentPId,
        uint256 offset,
        uint256 limit
    )
        external
        view
        returns (string[] memory result, uint256 total)
    {
        string[] storage all = _pChildrenOf[parentPId];
        total = all.length;
        if (offset >= total) return (new string[](0), total);
        uint256 end = offset + limit;
        if (end > total) end = total;
        result = new string[](end - offset);
        for (uint256 i = offset; i < end; i++) {
            result[i - offset] = all[i];
        }
    }

    // ─── Passport Registry — Physical ─────────────────────────────────────────

    function _validateOptionalImageSlots(
        bytes32 imageHash2,
        string calldata imageUrl2,
        bytes32 imageHash3,
        string calldata imageUrl3
    ) internal pure {
        if (imageHash2 == bytes32(0)) {
            if (!(bytes(imageUrl2).length == 0)) revert EC(41);
        } else {
            if (!(bytes(imageUrl2).length <= 512)) revert EC(40);
        }
        if (imageHash3 == bytes32(0)) {
            if (!(bytes(imageUrl3).length == 0)) revert EC(39);
        } else {
            if (!(bytes(imageUrl3).length <= 512)) revert EC(38);
            if (!(imageHash2 != bytes32(0))) revert EC(37);
        }
    }

    /**
     * Register a PHYSICAL object.
     *
     * Caller must be registered (profile ID mandatory).
     * At least one seal is required: sealType must be 1, 2, or 3.
     *
     * @param year          Any year > 0 (e.g. 1823 for historical art)
     * @param month         1–12
     * @param dataHash      SHA-256 of minified passport.json
     * @param dataUrl       Public URL of passport.json (max 512 chars). May be "" — verifiers cannot fetch JSON without a URL.
     * @param imageHash     SHA-256 of image. bytes32(0) = no image
     * @param imageUrl      Image URL hint. "" = no image
     * @param sealType      1 = NFC only, 2 = numbered only, 3 = both
     * @param sealHash      SHA-256 of seal object in passport.json
     * @param nfcPublicKey  NFC chip public key. "" = no NFC seal
     * @param nfcModel      Must be "NTAG424DNA_TT" if using NFC seal. "" = no NFC seal.
     *                      Only TagTamper variant accepted — standard NTAG424DNA is rejected.
     *                      TagTamper permanently records if seal is physically removed.
     * @param imageHash2/3  Optional additional image SHA-256 (max 3 hashes total including primary imageHash).
     */
    function _validatePhysical(
        uint32 year,
        uint8 month,
        bytes32 dataHash,
        string calldata dataUrl,
        bytes32 imageHash,
        string calldata imageUrl,
        uint8 sealType,
        bytes32 sealHash,
        bytes calldata nfcPublicKey,
        string calldata nfcModel,
        bytes32 imageHash2,
        string calldata imageUrl2,
        bytes32 imageHash3,
        string calldata imageUrl3
    ) internal pure {
        if (!(year > 0)) revert EC(9);
        if (!(month >= 1 && month <= 12)) revert EC(8);
        if (!(dataHash != bytes32(0))) revert EC(30);
        if (!(bytes(dataUrl).length <= 512)) revert EC(24);
        if (!(bytes(imageUrl).length <= 512)) revert EC(23);
        if (!(sealType >= 1 && sealType <= 3)) revert EC(36);
        if (!(sealHash != bytes32(0))) revert EC(35);

        if (sealType == 1 || sealType == 3) {
            if (!(nfcPublicKey.length > 0)) revert EC(34);
            if (!(keccak256(bytes(nfcModel)) == NFC_NTAG424DNA_TT_HASH)) revert EC(33);
        } else {
            if (!(bytes(nfcModel).length == 0)) revert EC(32);
        }

        if (imageHash == bytes32(0)) {
            if (!(bytes(imageUrl).length == 0)) revert EC(28);
        }

        _validateOptionalImageSlots(imageHash2, imageUrl2, imageHash3, imageUrl3);
    }

    /// @dev Strip trailing ASCII `/` only (repeated). Does not normalize `//` in the middle of the path;
    ///      callers should pass a clean HTTPS folder base; malformed bases may resolve to odd URLs.
    function _stripTrailingSlash(string calldata s) internal pure returns (string memory) {
        bytes memory b = bytes(s);
        uint256 end = b.length;
        while (end > 0 && b[end - 1] == 0x2f) {
            unchecked {
                end--;
            }
        }
        if (end == b.length) {
            return string(abi.encodePacked(s));
        }
        bytes memory out = new bytes(end);
        for (uint256 i = 0; i < end; i++) {
            out[i] = b[i];
        }
        return string(out);
    }

    /// @param dataUrl When `dataUrlIsFolderBase` is true, this is the HTTPS folder root only (no filename); the stored URL becomes `folderBase + "/" + humanId + ".json"` after `humanId` is known.
    function _resolveMintDataUrl(
        string calldata dataUrl,
        bool dataUrlIsFolderBase,
        string memory humanId
    ) internal pure returns (string memory) {
        if (bytes(dataUrl).length == 0) {
            if (!(!dataUrlIsFolderBase)) revert EC(31);
            return "";
        }
        if (!dataUrlIsFolderBase) {
            return string(abi.encodePacked(dataUrl));
        }
        string memory base = _stripTrailingSlash(dataUrl);
        return string(abi.encodePacked(base, "/", humanId, ".json"));
    }

    function mintPhysical(
        uint32  year,
        uint8   month,
        bytes32 dataHash,
        string  calldata dataUrl,
        bytes32 imageHash,
        string  calldata imageUrl,
        uint8   sealType,
        bytes32 sealHash,
        bytes   calldata nfcPublicKey,
        string  calldata nfcModel,
        bytes32 imageHash2,
        string  calldata imageUrl2,
        bytes32 imageHash3,
        string  calldata imageUrl3,
        bool dataUrlIsFolderBase
    ) external notFrozen returns (string memory humanId) {
        string memory creatorId = _beginMint();

        _validatePhysical(
            year,
            month,
            dataHash,
            dataUrl,
            imageHash,
            imageUrl,
            sealType,
            sealHash,
            nfcPublicKey,
            nfcModel,
            imageHash2,
            imageUrl2,
            imageHash3,
            imageUrl3
        );

        humanId = _generatePassportId(year, month);

        string memory resolvedDataUrl = _resolveMintDataUrl(dataUrl, dataUrlIsFolderBase, humanId);
        if (!(bytes(resolvedDataUrl).length <= 512)) revert EC(27);

        _passports[humanId] = Passport({
            humanId:         humanId,
            contractVersion: CONTRACT_VERSION,
            creator:         msg.sender,
            owner:           msg.sender,
            creatorId:       creatorId,
            year:            year,
            month:           month,
            objectType:      OBJECT_PHYSICAL,
            dataHash:     dataHash,
            imageHash:    imageHash,
            imageHash2:   imageHash2,
            imageHash3:   imageHash3,
            fileHash:     bytes32(0),
            sealType:     sealType,
            sealHash:     sealHash,
            nfcPublicKey: nfcPublicKey,
            nfcModel:     nfcModel,
            dataUrl:      resolvedDataUrl,
            imageUrl:     imageUrl,
            imageUrl2:    imageUrl2,
            imageUrl3:    imageUrl3,
            timestamp:    block.timestamp,
            revoked:      false,
            revokedAt:    0,
            revocationReasonHash: bytes32(0)
        });

        _creatorPassports[msg.sender].push(humanId);

        emit PassportMinted(humanId, msg.sender, creatorId, OBJECT_PHYSICAL,
                            year, month, dataHash, sealType, nfcModel, block.timestamp);
        return humanId;
    }

    // ─── Passport Registry — Digital ──────────────────────────────────────────

    /**
     * Register a DIGITAL object.
     *
     * Caller must be registered (profile ID mandatory).
     * No seal required. fileHash is mandatory.
     *
     * @param year          Any year > 0 (e.g. 1823 for historical art)
     * @param month         1–12
     * @param dataHash      SHA-256 of minified passport.json
     * @param dataUrl       Public URL of passport.json (max 512 chars). May be "" — verifiers cannot fetch JSON without a URL.
     * @param imageHash     SHA-256 of preview image. bytes32(0) = none
     * @param imageUrl      Preview image URL hint. "" = none
     * @param fileHash      SHA-256 of the original digital file. Required.
     * @param dataUrlIsFolderBase If true, `dataUrl` is folder root only; stored URL is `folderBase/humanId.json`.
     */
    function mintDigital(
        uint32  year,
        uint8   month,
        bytes32 dataHash,
        string  calldata dataUrl,
        bytes32 imageHash,
        string  calldata imageUrl,
        bytes32 imageHash2,
        string  calldata imageUrl2,
        bytes32 imageHash3,
        string  calldata imageUrl3,
        bytes32 fileHash,
        bool dataUrlIsFolderBase
    ) external notFrozen returns (string memory humanId) {
        string memory creatorId = _beginMint();

        if (!(year > 0)) revert EC(9);
        if (!(month >= 1   && month <= 12)) revert EC(8);
        if (!(dataHash != bytes32(0))) revert EC(30);
        if (!(bytes(dataUrl).length <= 512)) revert EC(24);
        if (!(bytes(imageUrl).length <= 512)) revert EC(23);
        if (!(fileHash != bytes32(0))) revert EC(29);

        if (imageHash == bytes32(0)) {
            if (!(bytes(imageUrl).length == 0)) revert EC(28);
        }
        _validateOptionalImageSlots(imageHash2, imageUrl2, imageHash3, imageUrl3);

        humanId = _generatePassportId(year, month);

        string memory resolvedDataUrl = _resolveMintDataUrl(dataUrl, dataUrlIsFolderBase, humanId);
        if (!(bytes(resolvedDataUrl).length <= 512)) revert EC(27);

        _passports[humanId] = Passport({
            humanId:         humanId,
            contractVersion: CONTRACT_VERSION,
            creator:         msg.sender,
            owner:           msg.sender,
            creatorId:       creatorId,
            year:            year,
            month:           month,
            objectType:      OBJECT_DIGITAL,
            dataHash:     dataHash,
            imageHash:    imageHash,
            imageHash2:   imageHash2,
            imageHash3:   imageHash3,
            fileHash:     fileHash,
            sealType:     0,
            sealHash:     bytes32(0),
            nfcPublicKey: "",
            nfcModel:     "",
            dataUrl:      resolvedDataUrl,
            imageUrl:     imageUrl,
            imageUrl2:    imageUrl2,
            imageUrl3:    imageUrl3,
            timestamp:    block.timestamp,
            revoked:      false,
            revokedAt:    0,
            revocationReasonHash: bytes32(0)
        });

        _creatorPassports[msg.sender].push(humanId);

        emit PassportMinted(humanId, msg.sender, creatorId, OBJECT_DIGITAL,
                            year, month, dataHash, 0, "", block.timestamp);
        return humanId;
    }

    // ─── Passport — Update ────────────────────────────────────────────────────

    function _canUpdatePassportUrls(Passport storage p) internal view returns (bool) {
        if (msg.sender == p.creator || msg.sender == p.owner) return true;
        DelegationInfo storage d = _creatorPublishDelegation[p.creator];
        return d.agent == msg.sender && d.expiresAt > block.timestamp;
    }

    /// Registered creator (`msg.sender`) designates a single wallet that may update hosted URLs for **all** their passports.
    function delegateCreatorPublishing(address agent, uint256 expiresAt) external notFrozen {
        if (!(agent != address(0))) revert EC(21);
        _requireRegistered();
        if (!(expiresAt > block.timestamp)) revert EC(20);
        _creatorPublishDelegation[msg.sender] = DelegationInfo({ agent: agent, expiresAt: expiresAt });
        emit CreatorPublishingDelegated(msg.sender, agent, expiresAt);
    }

    function revokeCreatorPublishing() external notFrozen {
        _requireRegistered();
        delete _creatorPublishDelegation[msg.sender];
        emit CreatorPublishingDelegationRevoked(msg.sender, block.timestamp);
    }

    function getCreatorPublishingDelegation(address creatorWallet)
        external
        view
        returns (address agent, uint256 expiresAt)
    {
        DelegationInfo storage d = _creatorPublishDelegation[creatorWallet];
        return (d.agent, d.expiresAt);
    }

    /**
     * Update hosting URLs only — dataUrl and imageUrl.
     * Use this when moving passport.json or image to a new host.
     *
     * ALL HASHES ARE IMMUTABLE after minting:
     *   dataHash, imageHash, fileHash, sealHash — cannot change ever.
     *
     * The caller must provide confirmedDataHash matching the on-chain dataHash.
     * This proves the caller knows the original content and prevents accidental
     * URL mistakes that would make the passport appear tampered.
     *
     * Note: this does NOT protect against a stolen wallet — dataHash is public
     * on-chain, so anyone with wallet access can read and pass it. This is a
     * UX safeguard, not a security mechanism.
     *
     * Authorized callers: passport **creator** or **owner**, or the **creator’s active publishing agent**
     * (`delegateCreatorPublishing` / `getCreatorPublishingDelegation`).
     *
     * Folder-base mint (`dataUrlIsFolderBase` on mint) only affects the **initial** stored URL.
     * This function always sets **literal** `newDataUrl` / `newImageUrl` (no folder resolution here).
     *
     * @param confirmedDataHash  Must equal the on-chain dataHash. Prevents
     *                           accidental URL updates pointing to wrong content.
     */
    function updatePassportUrls(
        string  calldata humanId,
        string  calldata newDataUrl,
        string  calldata newImageUrl,
        bytes32          confirmedDataHash
    ) external notFrozen {
        Passport storage p = _passports[humanId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!_canUpdatePassportUrls(p)) revert EC(26);
        if (!(p.dataHash == confirmedDataHash)) revert EC(25);
        if (!(bytes(newDataUrl).length <= 512)) revert EC(24);
        if (!(bytes(newImageUrl).length <= 512)) revert EC(23);

        // Only primary JSON + primary image URLs — hashes are immutable (extra image URLs unchanged here).
        p.dataUrl  = newDataUrl;
        p.imageUrl = newImageUrl;

        emit PassportUrlsUpdated(humanId, newDataUrl, newImageUrl);
    }

    /// Current owner (starts as creator) may transfer the passport record to a new wallet.
    function transferPassport(string calldata humanId, address newOwner) external notFrozen {
        if (!(newOwner != address(0))) revert EC(22);
        Passport storage p = _passports[humanId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(11);
        if (!(p.owner == msg.sender)) revert EC(19);
        p.owner = newOwner;
        emit PassportTransferred(humanId, msg.sender, newOwner, block.timestamp);
    }

    /**
     * Irreversible passport revocation. Creator or governance may revoke.
     * reasonHash should be keccak256(utf8(reason)) for verifiers; full text may live off-chain.
     */
    function revokePassport(string calldata humanId, bytes32 reasonHash) external notFrozen {
        Passport storage p = _passports[humanId];
        if (!(p.creator != address(0))) revert EC(12);
        if (!(!p.revoked)) revert EC(18);
        if (!(msg.sender == p.creator || msg.sender == governance)) revert EC(17);
        if (!(reasonHash != bytes32(0))) revert EC(16);
        p.revoked = true;
        p.revokedAt = block.timestamp;
        p.revocationReasonHash = reasonHash;
        emit PassportRevoked(humanId, msg.sender, reasonHash, block.timestamp);
    }

    /**
     * P or M institution raises an authenticity / counterfeit concern (institutional opinion, not a legal finding).
     */
    function raiseCounterfeitConcern(string calldata humanId, bytes32 reasonHash) external notFrozen {
        if (!(reasonHash != bytes32(0))) revert EC(16);
        Passport storage p = _passports[humanId];
        if (!(p.creator != address(0))) revert EC(12);

        string memory callerId = _walletToCreatorId[msg.sender];
        if (!(bytes(callerId).length > 0)) revert EC(7);
        bytes1 tp = _creators[callerId].typePrefix;
        if (!(tp == TYPE_P || tp == TYPE_M)) revert EC(15);

        _counterfeitActive[humanId] = true;
        _counterfeitProverId[humanId] = callerId;
        _counterfeitReasonHash[humanId] = reasonHash;
        _counterfeitTimestamp[humanId] = block.timestamp;
        emit CounterfeitConcernRaised(humanId, callerId, reasonHash, block.timestamp);
    }

    /// Only the institution that raised the concern may clear it (v0.3 minimal policy).
    function clearCounterfeitConcern(string calldata humanId) external notFrozen {
        if (!(_counterfeitActive[humanId])) revert EC(14);
        string memory callerId = _requireRegistered();
        if (!(keccak256(bytes(_counterfeitProverId[humanId])) == keccak256(bytes(callerId)))) revert EC(13);
        _counterfeitActive[humanId] = false;
        emit CounterfeitConcernCleared(humanId, callerId, block.timestamp);
    }

    function getCounterfeitConcern(string calldata humanId)
        external
        view
        returns (
            bool active,
            string memory proverCreatorId,
            bytes32 reasonHash,
            uint256 ts
        )
    {
        active = _counterfeitActive[humanId];
        proverCreatorId = _counterfeitProverId[humanId];
        reasonHash = _counterfeitReasonHash[humanId];
        ts = _counterfeitTimestamp[humanId];
    }

    // ─── Passport — Read ──────────────────────────────────────────────────────

    function getPassport(string calldata humanId)
        external view returns (Passport memory)
    {
        if (!(_passports[humanId].creator != address(0))) revert EC(12);
        return _passports[humanId];
    }

    function exists(string calldata humanId) external view returns (bool) {
        return _passports[humanId].creator != address(0);
    }

    /**
     * Unified passport resolver — v1 architecture.
     *
     * Returns passport + creator + proof count in one call.
     * Verifiers use this as the single entry point regardless of contract version.
     * In v1, this function will also handle legacy lookups via merkle proof.
     *
     * Returns: (passport, creatorRecord, proofCount, contractVersion)
     */
    function resolvePassport(string calldata humanId)
        external
        view
        returns (
            Passport    memory passport,
            CreatorRecord memory creator,
            uint256             proofCount,
            uint8               version
        )
    {
        passport   = _passports[humanId];
        if (!(passport.creator != address(0))) revert EC(12);
        creator    = _creators[passport.creatorId];
        proofCount = _passportProofs[humanId].length;
        version    = CONTRACT_VERSION;
    }

    function getPassportsByCreator(address creator)
        external view returns (string[] memory)
    {
        return _creatorPassports[creator];
    }

    // Paginated — use when creator may have many passports
    function getPassportsByCreatorPaged(address creator, uint256 offset, uint256 limit)
        external view returns (string[] memory result, uint256 total)
    {
        string[] storage all = _creatorPassports[creator];
        total = all.length;
        if (offset >= total) return (new string[](0), total);
        uint256 end = offset + limit;
        if (end > total) end = total;
        result = new string[](end - offset);
        for (uint256 i = offset; i < end; i++) {
            result[i - offset] = all[i];
        }
    }

    function getProofsForPassportPaged(string calldata humanId, uint256 offset, uint256 limit)
        external view returns (string[] memory result, uint256 total)
    {
        string[] storage all = _passportProofs[humanId];
        total = all.length;
        if (offset >= total) return (new string[](0), total);
        uint256 end = offset + limit;
        if (end > total) end = total;
        result = new string[](end - offset);
        for (uint256 i = offset; i < end; i++) {
            result[i - offset] = all[i];
        }
    }

    // ─── Proof Registry ───────────────────────────────────────────────────────

    /**
     * Submit a Proof attestation for a registered passport.
     * Caller must be registered as type P (Proof Institution) or M (Museum).
     *
     * @param humanId   The passport being attested
     * @param noteHash  SHA-256 of attached document. bytes32(0) = none
     * @param noteUrl   URL of attached document. "" = none
     * @param year      Year of the proof event (e.g. 2031) — for readable PRF ID
     * @param month     Month of the proof event (1–12)
     *
     * Caller provides year+month explicitly to avoid on-chain timestamp approximation.
     * The exact block timestamp is always stored in ProofRecord.timestamp as well.
     */
    function submitProof(
        string  calldata humanId,
        bytes32          noteHash,
        string  calldata noteUrl,
        uint32           year,
        uint8            month
    ) external notFrozen returns (string memory proofId) {
        Passport storage pPass = _passports[humanId];
        if (!(pPass.creator != address(0))) revert EC(12);
        if (!(!pPass.revoked)) revert EC(11);
        if (!(bytes(noteUrl).length <= 512)) revert EC(10);
        if (!(year > 0)) revert EC(9);
        if (!(month >= 1 && month <= 12)) revert EC(8);

        string memory callerId = _walletToCreatorId[msg.sender];
        if (!(bytes(callerId).length > 0)) revert EC(7);
        bytes1 tp = _creators[callerId].typePrefix;
        if (!(tp == TYPE_P || tp == TYPE_M)) revert EC(6);

        if (noteHash == bytes32(0)) {
            if (!(bytes(noteUrl).length == 0)) revert EC(5);
        }

        proofId = _generateProofId(year, month, humanId);

        _proofs[proofId] = ProofRecord({
            proofId:         proofId,
            contractVersion: CONTRACT_VERSION,
            prover:          callerId,
            humanId:         humanId,
            noteHash:        noteHash,
            noteUrl:         noteUrl,
            timestamp:       block.timestamp
        });

        _passportProofs[humanId].push(proofId);
        _institutionProofs[callerId].push(proofId);

        emit ProofSubmitted(proofId, humanId, callerId, block.timestamp);
        return proofId;
    }

    function getProofsForPassport(string calldata humanId)
        external view returns (string[] memory)
    {
        return _passportProofs[humanId];
    }

    function getProof(string calldata proofId)
        external view returns (ProofRecord memory)
    {
        if (!(bytes(_proofs[proofId].proofId).length > 0)) revert EC(4);
        return _proofs[proofId];
    }

    function getProofsByInstitution(string calldata creatorId)
        external view returns (string[] memory)
    {
        return _institutionProofs[creatorId];
    }

    // ─── Internal: validation ─────────────────────────────────────────────────

    function _requireRegistered() internal view returns (string memory creatorId) {
        creatorId = _walletToCreatorId[msg.sender];
        if (!(bytes(creatorId).length > 0)) revert EC(3);
    }

    /** Enforce registration and monthly limit (no protocol fee). */
    function _beginMint() internal returns (string memory creatorId) {
        creatorId = _requireRegistered();
        _checkAndIncrementMintLimit(creatorId);
    }

    function _isValidType(bytes1 t) internal pure returns (bool) {
        return t == TYPE_C || t == TYPE_B || t == TYPE_P || t == TYPE_M;
    }

    function _requireTypeP(string memory creatorId, string memory err) internal view {
        CreatorRecord storage c = _creators[creatorId];
        if (!(bytes(c.creatorId).length > 0)) revert EC(2);
        require(c.typePrefix == TYPE_P, err);
    }

    /**
     * Check monthly mint limit and increment counter (C/B only; P and M are unlimited).
     * Resets on calendar month boundary (yearMonth key changes).
     */
    function _checkAndIncrementMintLimit(string memory creatorId) internal {
        bytes1 t = _creators[creatorId].typePrefix;
        if (t == TYPE_P || t == TYPE_M) {
            return;
        }
        uint32 limit = (t == TYPE_B) ? MONTHLY_LIMIT_B : MONTHLY_LIMIT_C;
        uint32 ym = _currentYearMonth();
        uint32 count = _mintCount[msg.sender][ym];
        if (!(count < limit)) revert EC(1);
        _mintCount[msg.sender][ym] = count + 1;
    }

    /**
     * Returns current year*100+month as uint32 key.
     * Used for calendar-month rate limiting.
     */
    function _currentYearMonth() internal view returns (uint32) {
        uint32 year  = _currentYear();
        uint8  month = _currentMonth();
        // Note: approximate calculation may have ±1 month drift at year boundaries.
        // This affects only rate limit buckets, not passport/proof records.
        // Rate limit resets are cosmetic — a slight drift is acceptable.
        return year * 100 + uint32(month);
    }

    /**
     * Get remaining mints for a wallet in the current calendar month.
     * For P- and M-type creators, returns `type(uint32).max` (unlimited).
     */
    function getRemainingMints(address wallet) external view returns (uint32) {
        string memory cid = _walletToCreatorId[wallet];
        if (bytes(cid).length == 0) {
            return 0;
        }
        bytes1 t = _creators[cid].typePrefix;
        if (t == TYPE_P || t == TYPE_M) {
            return type(uint32).max;
        }
        uint32 limit = (t == TYPE_B) ? MONTHLY_LIMIT_B : MONTHLY_LIMIT_C;
        uint32 ym = _currentYearMonth();
        uint32 used = _mintCount[wallet][ym];
        if (used >= limit) return 0;
        return limit - used;
    }

    // ─── Internal: ID generation ──────────────────────────────────────────────

    /**
     * Generate a unique profile ID number (0–999,999,999,999).
     * Uses keccak256 entropy with nonce. Retries on collision (max 25 attempts).
     */
    function _generateCreatorNumber() internal returns (uint64) {
        uint256 baseNonce = _creatorNonce;
        for (uint i = 0; i < 25; i++) {
            // Combine multiple sources for better unpredictability.
            // Note: on-chain entropy is never truly random — IDs are not
            // security-critical (no funds at stake), so this is acceptable.
            uint64 n = uint64(uint256(keccak256(abi.encodePacked(
                block.timestamp,
                block.prevrandao,   // replaces block.difficulty post-Merge
                msg.sender,
                baseNonce + i,
                gasleft()
            ))) % 1_000_000_000_000);
            if (!_creatorNumberTaken[n]) {
                _creatorNonce = baseNonce + i + 1;
                return n;
            }
        }
        revert EC(62);
    }

    /**
     * Generate a unique Passport ID number (0–999,999,999) for year+month.
     * Uses keccak256 entropy with nonce. Retries on collision (max 25 attempts).
     */
    function _generatePassportId(uint32 year, uint8 month)
        internal returns (string memory)
    {
        uint32 key = uint32(year) * 100 + uint32(month);
        uint256 baseNonce = _passportNonce;
        for (uint i = 0; i < 25; i++) {
            uint32 n = uint32(uint256(keccak256(abi.encodePacked(
                block.timestamp,
                block.prevrandao,
                msg.sender,
                baseNonce + i,
                key,
                gasleft()
            ))) % 1_000_000_000);
            if (!_passportNumberTaken[key][n]) {
                _passportNonce = baseNonce + i + 1;
                _passportNumberTaken[key][n] = true;
                return string(abi.encodePacked(
                    "ODP-",
                    _yearToString(year), "-",
                    _monthToString(month), "-",
                    _pad9(n)
                ));
            }
        }
        revert EC(61);
    }

    /**
     * Generate a unique Proof ID number (0–99,999,999) for year+month.
     */
    function _generateProofId(uint32 year, uint8 month, string memory humanId)
        internal returns (string memory)
    {
        uint32 key = uint32(year) * 100 + uint32(month);
        uint256 baseNonce = _proofNonce;
        bytes32 humanIdHash = keccak256(bytes(humanId));
        for (uint i = 0; i < 25; i++) {
            uint32 n = uint32(uint256(keccak256(abi.encodePacked(
                block.timestamp,
                block.prevrandao,
                msg.sender,
                baseNonce + i,
                key,
                humanIdHash,
                gasleft()
            ))) % 100_000_000);
            if (!_proofNumberTaken[key][n]) {
                _proofNonce = baseNonce + i + 1;
                _proofNumberTaken[key][n] = true;
                return string(abi.encodePacked(
                    "PRF-",
                    _yearToString(year), "-",
                    _monthToString(month), "-",
                    _pad8(n)
                ));
            }
        }
        revert EC(60);
    }

    // ─── Internal: string builders ────────────────────────────────────────────

    // "C-482-930-174-005"
    function _buildCreatorId(bytes1 typePrefix, uint64 number)
        internal pure returns (string memory)
    {
        return string(abi.encodePacked(
            string(abi.encodePacked(typePrefix)), "-",
            _pad3(uint32(number / 1_000_000_000)), "-",
            _pad3(uint32((number / 1_000_000) % 1_000)), "-",
            _pad3(uint32((number / 1_000) % 1_000)), "-",
            _pad3(uint32(number % 1_000))
        ));
    }

    // ─── Internal: time helpers ───────────────────────────────────────────────
    //
    // These functions compute approximate year and month from block.timestamp.
    // They are used ONLY for generating cosmetic ProofRecord IDs (PRF-YYYY-MM-...).
    // The exact blockchain timestamp is always stored separately in ProofRecord.timestamp.
    // A slight drift (±1 month at year boundaries) does not affect security or correctness.

    function _currentYear() internal view returns (uint32) {
        // Average Gregorian year = 365.2425 days = 31,556,952 seconds
        return uint32(1970 + block.timestamp / 31_556_952);
    }

    function _currentMonth() internal view returns (uint8) {
        // Seconds elapsed within the current year (approximate)
        uint256 secsInYear = block.timestamp % 31_556_952;
        // Average month = 31,556,952 / 12 = 2,629,746 seconds
        uint256 m = secsInYear / 2_629_746 + 1;
        if (m > 12) m = 12;
        return uint8(m);
    }

    // ─── Internal: string formatters ──────────────────────────────────────────

    function _yearToString(uint32 v) internal pure returns (string memory) {
        // Dynamic length — no leading zeros for historical years (e.g. "823", not "0823")
        if (v == 0) return "0";
        uint32 temp = v;
        uint len = 0;
        while (temp > 0) { len++; temp /= 10; }
        bytes memory b = new bytes(len);
        for (uint i = len; i > 0; i--) { b[i-1] = bytes1(uint8(48 + v % 10)); v /= 10; }
        return string(b);
    }

    function _monthToString(uint8 v) internal pure returns (string memory) {
        bytes memory b = new bytes(2);
        b[1] = bytes1(uint8(48 + v % 10));
        b[0] = bytes1(uint8(48 + (v / 10) % 10));
        return string(b);
    }

    function _pad8(uint32 v) internal pure returns (string memory) {
        bytes memory b = new bytes(8);
        for (uint i = 8; i > 0; i--) { b[i-1] = bytes1(uint8(48 + v % 10)); v /= 10; }
        return string(b);
    }

    function _pad9(uint32 v) internal pure returns (string memory) {
        bytes memory b = new bytes(9);
        for (uint i = 9; i > 0; i--) { b[i-1] = bytes1(uint8(48 + v % 10)); v /= 10; }
        return string(b);
    }

    function _pad3(uint32 v) internal pure returns (string memory) {
        bytes memory b = new bytes(3);
        b[2] = bytes1(uint8(48 + v % 10));
        b[1] = bytes1(uint8(48 + (v / 10) % 10));
        b[0] = bytes1(uint8(48 + (v / 100) % 10));
        return string(b);
    }
}
