/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
    export type PassportCoreMintInputsStruct = {year: BigNumberish, month: BigNumberish, title: string, authorName: string, shortDescription: string, domain: string, contentClass: BigNumberish, lifecycleStatus: BigNumberish, aiStatus: BigNumberish, verificationMethod: BigNumberish, editionModel: BigNumberish}

    export type PassportCoreMintInputsStructOutput = [year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint] & {year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint }
  

    export type PassportMintInputsStruct = {core: PassportCoreMintInputsStruct, dataHash: BytesLike, dataUrl: string, imageHash: BytesLike, imageUrl: string, fileHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish, initialOwner: AddressLike}

    export type PassportMintInputsStructOutput = [core: PassportCoreMintInputsStructOutput, dataHash: string, dataUrl: string, imageHash: string, imageUrl: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, initialOwner: string] & {core: PassportCoreMintInputsStructOutput, dataHash: string, dataUrl: string, imageHash: string, imageUrl: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, initialOwner: string }
  

export declare namespace IODPRegistryForUnits {
      
    export type CreatorRecordStruct = {creatorId: string, wallet: AddressLike, typePrefix: BytesLike, timestamp: BigNumberish}

    export type CreatorRecordStructOutput = [creatorId: string, wallet: string, typePrefix: string, timestamp: bigint] & {creatorId: string, wallet: string, typePrefix: string, timestamp: bigint }
  

    export type PassportHeaderViewStruct = {passportId: string, contractVersion: BigNumberish, creator: AddressLike, owner: AddressLike, creatorId: string, year: BigNumberish, month: BigNumberish, title: string, authorName: string, shortDescription: string, domain: string, objectType: string}

    export type PassportHeaderViewStructOutput = [passportId: string, contractVersion: bigint, creator: string, owner: string, creatorId: string, year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, objectType: string] & {passportId: string, contractVersion: bigint, creator: string, owner: string, creatorId: string, year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, objectType: string }
  
    }

  export interface IODPRegistryForUnitsInterface extends Interface {
    getFunction(nameOrSignature: "getCreator" | "getPassportHeader" | "lockEditionRevocation" | "mintUnitPassport"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getCreator', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportHeader', values: [string]): string;
encodeFunctionData(functionFragment: 'lockEditionRevocation', values: [string]): string;
encodeFunctionData(functionFragment: 'mintUnitPassport', values: [PassportMintInputsStruct, string, AddressLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'getCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportHeader', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockEditionRevocation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintUnitPassport', data: BytesLike): Result;
  }

  

  export interface IODPRegistryForUnits extends BaseContract {
    
    connect(runner?: ContractRunner | null): IODPRegistryForUnits;
    waitForDeployment(): Promise<this>;

    interface: IODPRegistryForUnitsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getCreator: TypedContractMethod<
      [creatorId: string, ],
      [IODPRegistryForUnits.CreatorRecordStructOutput],
      'view'
    >
    

    
    getPassportHeader: TypedContractMethod<
      [passportId: string, ],
      [IODPRegistryForUnits.PassportHeaderViewStructOutput],
      'view'
    >
    

    
    lockEditionRevocation: TypedContractMethod<
      [passportId: string, ],
      [void],
      'nonpayable'
    >
    

    
    mintUnitPassport: TypedContractMethod<
      [m: PassportMintInputsStruct, editionPassportId: string, unitOwner: AddressLike, dataUrlIsFolderBase: boolean, ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getCreator'): TypedContractMethod<
      [creatorId: string, ],
      [IODPRegistryForUnits.CreatorRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportHeader'): TypedContractMethod<
      [passportId: string, ],
      [IODPRegistryForUnits.PassportHeaderViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'lockEditionRevocation'): TypedContractMethod<
      [passportId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintUnitPassport'): TypedContractMethod<
      [m: PassportMintInputsStruct, editionPassportId: string, unitOwner: AddressLike, dataUrlIsFolderBase: boolean, ],
      [string],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }