/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
    export type PassportCoreMintInputsStruct = {year: BigNumberish, month: BigNumberish, title: string, authorName: string, shortDescription: string, domain: string, contentClass: BigNumberish, lifecycleStatus: BigNumberish, aiStatus: BigNumberish, verificationMethod: BigNumberish, editionModel: BigNumberish}

    export type PassportCoreMintInputsStructOutput = [year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint] & {year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint }
  

    export type PassportMintInputsStruct = {core: PassportCoreMintInputsStruct, dataHash: BytesLike, dataUrl: string, imageHash: BytesLike, imageUrl: string, fileHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish, initialOwner: AddressLike}

    export type PassportMintInputsStructOutput = [core: PassportCoreMintInputsStructOutput, dataHash: string, dataUrl: string, imageHash: string, imageUrl: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, initialOwner: string] & {core: PassportCoreMintInputsStructOutput, dataHash: string, dataUrl: string, imageHash: string, imageUrl: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint, initialOwner: string }
  

export declare namespace ObjectDigitalPassport {
      
    export type CreatorRecordStruct = {creatorId: string, wallet: AddressLike, typePrefix: BytesLike, timestamp: BigNumberish}

    export type CreatorRecordStructOutput = [creatorId: string, wallet: string, typePrefix: string, timestamp: bigint] & {creatorId: string, wallet: string, typePrefix: string, timestamp: bigint }
  

    export type PassportClassificationViewStruct = {contentClass: BigNumberish, lifecycleStatus: BigNumberish, aiStatus: BigNumberish, verificationMethod: BigNumberish, editionModel: BigNumberish, timestamp: BigNumberish, revoked: boolean, revokedAt: BigNumberish, revocationReasonHash: BytesLike, mintAgent: AddressLike}

    export type PassportClassificationViewStructOutput = [contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint, timestamp: bigint, revoked: boolean, revokedAt: bigint, revocationReasonHash: string, mintAgent: string] & {contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint, timestamp: bigint, revoked: boolean, revokedAt: bigint, revocationReasonHash: string, mintAgent: string }
  

    export type PassportEventsViewStruct = {eventCount: BigNumberish, lastEventKind: BigNumberish, lastEventAt: BigNumberish, lifecycleStatus: BigNumberish}

    export type PassportEventsViewStructOutput = [eventCount: bigint, lastEventKind: bigint, lastEventAt: bigint, lifecycleStatus: bigint] & {eventCount: bigint, lastEventKind: bigint, lastEventAt: bigint, lifecycleStatus: bigint }
  

    export type PassportHeaderViewStruct = {passportId: string, contractVersion: BigNumberish, creator: AddressLike, owner: AddressLike, creatorId: string, year: BigNumberish, month: BigNumberish, title: string, authorName: string, shortDescription: string, domain: string, objectType: string}

    export type PassportHeaderViewStructOutput = [passportId: string, contractVersion: bigint, creator: string, owner: string, creatorId: string, year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, objectType: string] & {passportId: string, contractVersion: bigint, creator: string, owner: string, creatorId: string, year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, objectType: string }
  

    export type PassportMediaViewStruct = {dataHash: BytesLike, dataUrl: string, imageHash: BytesLike, imageUrl: string, fileHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish}

    export type PassportMediaViewStructOutput = [dataHash: string, dataUrl: string, imageHash: string, imageUrl: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint] & {dataHash: string, dataUrl: string, imageHash: string, imageUrl: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint }
  
    }

  export interface ObjectDigitalPassportInterface extends Interface {
    getFunction(nameOrSignature: "CONTRACT_VERSION" | "deployer" | "editionUnits" | "freeze" | "frozen" | "getCreator" | "getCreatorByWallet" | "getPassportClassification" | "getPassportEvents" | "getPassportHeader" | "getPassportMedia" | "getPassportsByCreatorPaged" | "governance" | "isRevocationLocked" | "lockEditionRevocation" | "mintDigital" | "mintMixed" | "mintPhysical" | "recordPassportEvent" | "registerCreator" | "revokePassport" | "setEditionUnits" | "setExtensionRouter" | "setRelationsSatellite" | "transferGovernance" | "transferPassport" | "updatePassportUrls"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CreatorRegistered" | "PassportEventRecorded" | "PassportMinted" | "PassportRevoked" | "PassportTransferred" | "PassportUrlsUpdated" | "RegistryFrozen"): EventFragment;

    encodeFunctionData(functionFragment: 'CONTRACT_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'deployer', values?: undefined): string;
encodeFunctionData(functionFragment: 'editionUnits', values?: undefined): string;
encodeFunctionData(functionFragment: 'freeze', values?: undefined): string;
encodeFunctionData(functionFragment: 'frozen', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCreator', values: [string]): string;
encodeFunctionData(functionFragment: 'getCreatorByWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPassportClassification', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportEvents', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportHeader', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportMedia', values: [string]): string;
encodeFunctionData(functionFragment: 'getPassportsByCreatorPaged', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'governance', values?: undefined): string;
encodeFunctionData(functionFragment: 'isRevocationLocked', values: [string]): string;
encodeFunctionData(functionFragment: 'lockEditionRevocation', values: [string]): string;
encodeFunctionData(functionFragment: 'mintDigital', values: [PassportMintInputsStruct, boolean, string]): string;
encodeFunctionData(functionFragment: 'mintMixed', values: [PassportMintInputsStruct, boolean, string]): string;
encodeFunctionData(functionFragment: 'mintPhysical', values: [PassportMintInputsStruct, boolean, string]): string;
encodeFunctionData(functionFragment: 'recordPassportEvent', values: [string, BigNumberish, BigNumberish, string, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'registerCreator', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'revokePassport', values: [string, BytesLike]): string;
encodeFunctionData(functionFragment: 'setEditionUnits', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setExtensionRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRelationsSatellite', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferGovernance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferPassport', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePassportUrls', values: [string, string, string, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'CONTRACT_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'editionUnits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freeze', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'frozen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorByWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportClassification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportEvents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportHeader', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportMedia', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPassportsByCreatorPaged', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'governance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRevocationLocked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockEditionRevocation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintDigital', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintMixed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintPhysical', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordPassportEvent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokePassport', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEditionUnits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExtensionRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRelationsSatellite', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferGovernance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferPassport', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePassportUrls', data: BytesLike): Result;
  }

  
    export namespace CreatorRegisteredEvent {
      export type InputTuple = [creatorId: string, wallet: AddressLike, typePrefix: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [creatorId: string, wallet: string, typePrefix: string, timestamp: bigint];
      export interface OutputObject {creatorId: string, wallet: string, typePrefix: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassportEventRecordedEvent {
      export type InputTuple = [passportId: string, kind: BigNumberish, value: BigNumberish, note: string, attachmentHash: BytesLike, attachmentUrl: string, recordedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, kind: bigint, value: bigint, note: string, attachmentHash: string, attachmentUrl: string, recordedBy: string, timestamp: bigint];
      export interface OutputObject {passportId: string, kind: bigint, value: bigint, note: string, attachmentHash: string, attachmentUrl: string, recordedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassportMintedEvent {
      export type InputTuple = [passportId: string, creator: AddressLike, creatorId: string, title: string, authorName: string, domain: string, objectType: string, contentClass: BigNumberish, year: BigNumberish, month: BigNumberish, dataHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish, timestamp: BigNumberish, mintAgent: AddressLike];
      export type OutputTuple = [passportId: string, creator: string, creatorId: string, title: string, authorName: string, domain: string, objectType: string, contentClass: bigint, year: bigint, month: bigint, dataHash: string, anchorsHash: string, anchorTypesMask: bigint, timestamp: bigint, mintAgent: string];
      export interface OutputObject {passportId: string, creator: string, creatorId: string, title: string, authorName: string, domain: string, objectType: string, contentClass: bigint, year: bigint, month: bigint, dataHash: string, anchorsHash: string, anchorTypesMask: bigint, timestamp: bigint, mintAgent: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassportRevokedEvent {
      export type InputTuple = [passportId: string, revokedBy: AddressLike, reasonHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, revokedBy: string, reasonHash: string, timestamp: bigint];
      export interface OutputObject {passportId: string, revokedBy: string, reasonHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassportTransferredEvent {
      export type InputTuple = [passportId: string, from: AddressLike, to: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: string, from: string, to: string, timestamp: bigint];
      export interface OutputObject {passportId: string, from: string, to: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PassportUrlsUpdatedEvent {
      export type InputTuple = [passportId: string, newDataUrl: string, newImageUrl: string];
      export type OutputTuple = [passportId: string, newDataUrl: string, newImageUrl: string];
      export interface OutputObject {passportId: string, newDataUrl: string, newImageUrl: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegistryFrozenEvent {
      export type InputTuple = [by: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [by: string, timestamp: bigint];
      export interface OutputObject {by: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ObjectDigitalPassport extends BaseContract {
    
    connect(runner?: ContractRunner | null): ObjectDigitalPassport;
    waitForDeployment(): Promise<this>;

    interface: ObjectDigitalPassportInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    CONTRACT_VERSION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deployer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    editionUnits: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    freeze: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    frozen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    getCreator: TypedContractMethod<
      [creatorId: string, ],
      [ObjectDigitalPassport.CreatorRecordStructOutput],
      'view'
    >
    

    
    getCreatorByWallet: TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >
    

    
    getPassportClassification: TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportClassificationViewStructOutput],
      'view'
    >
    

    
    getPassportEvents: TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportEventsViewStructOutput],
      'view'
    >
    

    
    getPassportHeader: TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportHeaderViewStructOutput],
      'view'
    >
    

    
    getPassportMedia: TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportMediaViewStructOutput],
      'view'
    >
    

    
    getPassportsByCreatorPaged: TypedContractMethod<
      [creator: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {result: string[], total: bigint }],
      'view'
    >
    

    
    governance: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isRevocationLocked: TypedContractMethod<
      [passportId: string, ],
      [boolean],
      'view'
    >
    

    
    lockEditionRevocation: TypedContractMethod<
      [passportId: string, ],
      [void],
      'nonpayable'
    >
    

    
    mintDigital: TypedContractMethod<
      [m: PassportMintInputsStruct, dataUrlIsFolderBase: boolean, mintOnBehalfOfCreatorId: string, ],
      [string],
      'nonpayable'
    >
    

    
    mintMixed: TypedContractMethod<
      [m: PassportMintInputsStruct, dataUrlIsFolderBase: boolean, mintOnBehalfOfCreatorId: string, ],
      [string],
      'nonpayable'
    >
    

    
    mintPhysical: TypedContractMethod<
      [m: PassportMintInputsStruct, dataUrlIsFolderBase: boolean, mintOnBehalfOfCreatorId: string, ],
      [string],
      'nonpayable'
    >
    

    
    recordPassportEvent: TypedContractMethod<
      [passportId: string, kind: BigNumberish, value: BigNumberish, note: string, attachmentHash: BytesLike, attachmentUrl: string, ],
      [void],
      'nonpayable'
    >
    

    
    registerCreator: TypedContractMethod<
      [typePrefix: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    revokePassport: TypedContractMethod<
      [passportId: string, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setEditionUnits: TypedContractMethod<
      [units: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setExtensionRouter: TypedContractMethod<
      [router: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRelationsSatellite: TypedContractMethod<
      [satellite: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferGovernance: TypedContractMethod<
      [newGovernance: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferPassport: TypedContractMethod<
      [passportId: string, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePassportUrls: TypedContractMethod<
      [passportId: string, newDataUrl: string, newImageUrl: string, confirmedDataHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'CONTRACT_VERSION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deployer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'editionUnits'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'freeze'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'frozen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getCreator'): TypedContractMethod<
      [creatorId: string, ],
      [ObjectDigitalPassport.CreatorRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorByWallet'): TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportClassification'): TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportClassificationViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportEvents'): TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportEventsViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportHeader'): TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportHeaderViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportMedia'): TypedContractMethod<
      [passportId: string, ],
      [ObjectDigitalPassport.PassportMediaViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getPassportsByCreatorPaged'): TypedContractMethod<
      [creator: AddressLike, offset: BigNumberish, limit: BigNumberish, ],
      [[string[], bigint] & {result: string[], total: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'governance'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isRevocationLocked'): TypedContractMethod<
      [passportId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'lockEditionRevocation'): TypedContractMethod<
      [passportId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintDigital'): TypedContractMethod<
      [m: PassportMintInputsStruct, dataUrlIsFolderBase: boolean, mintOnBehalfOfCreatorId: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintMixed'): TypedContractMethod<
      [m: PassportMintInputsStruct, dataUrlIsFolderBase: boolean, mintOnBehalfOfCreatorId: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintPhysical'): TypedContractMethod<
      [m: PassportMintInputsStruct, dataUrlIsFolderBase: boolean, mintOnBehalfOfCreatorId: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordPassportEvent'): TypedContractMethod<
      [passportId: string, kind: BigNumberish, value: BigNumberish, note: string, attachmentHash: BytesLike, attachmentUrl: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerCreator'): TypedContractMethod<
      [typePrefix: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokePassport'): TypedContractMethod<
      [passportId: string, reasonHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEditionUnits'): TypedContractMethod<
      [units: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setExtensionRouter'): TypedContractMethod<
      [router: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRelationsSatellite'): TypedContractMethod<
      [satellite: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferGovernance'): TypedContractMethod<
      [newGovernance: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferPassport'): TypedContractMethod<
      [passportId: string, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePassportUrls'): TypedContractMethod<
      [passportId: string, newDataUrl: string, newImageUrl: string, confirmedDataHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CreatorRegistered'): TypedContractEvent<CreatorRegisteredEvent.InputTuple, CreatorRegisteredEvent.OutputTuple, CreatorRegisteredEvent.OutputObject>;
getEvent(key: 'PassportEventRecorded'): TypedContractEvent<PassportEventRecordedEvent.InputTuple, PassportEventRecordedEvent.OutputTuple, PassportEventRecordedEvent.OutputObject>;
getEvent(key: 'PassportMinted'): TypedContractEvent<PassportMintedEvent.InputTuple, PassportMintedEvent.OutputTuple, PassportMintedEvent.OutputObject>;
getEvent(key: 'PassportRevoked'): TypedContractEvent<PassportRevokedEvent.InputTuple, PassportRevokedEvent.OutputTuple, PassportRevokedEvent.OutputObject>;
getEvent(key: 'PassportTransferred'): TypedContractEvent<PassportTransferredEvent.InputTuple, PassportTransferredEvent.OutputTuple, PassportTransferredEvent.OutputObject>;
getEvent(key: 'PassportUrlsUpdated'): TypedContractEvent<PassportUrlsUpdatedEvent.InputTuple, PassportUrlsUpdatedEvent.OutputTuple, PassportUrlsUpdatedEvent.OutputObject>;
getEvent(key: 'RegistryFrozen'): TypedContractEvent<RegistryFrozenEvent.InputTuple, RegistryFrozenEvent.OutputTuple, RegistryFrozenEvent.OutputObject>;

    filters: {
      
      'CreatorRegistered(string,address,bytes1,uint256)': TypedContractEvent<CreatorRegisteredEvent.InputTuple, CreatorRegisteredEvent.OutputTuple, CreatorRegisteredEvent.OutputObject>;
      CreatorRegistered: TypedContractEvent<CreatorRegisteredEvent.InputTuple, CreatorRegisteredEvent.OutputTuple, CreatorRegisteredEvent.OutputObject>;
    

      'PassportEventRecorded(string,uint8,uint8,string,bytes32,string,address,uint256)': TypedContractEvent<PassportEventRecordedEvent.InputTuple, PassportEventRecordedEvent.OutputTuple, PassportEventRecordedEvent.OutputObject>;
      PassportEventRecorded: TypedContractEvent<PassportEventRecordedEvent.InputTuple, PassportEventRecordedEvent.OutputTuple, PassportEventRecordedEvent.OutputObject>;
    

      'PassportMinted(string,address,string,string,string,string,string,uint8,uint32,uint8,bytes32,bytes32,uint32,uint256,address)': TypedContractEvent<PassportMintedEvent.InputTuple, PassportMintedEvent.OutputTuple, PassportMintedEvent.OutputObject>;
      PassportMinted: TypedContractEvent<PassportMintedEvent.InputTuple, PassportMintedEvent.OutputTuple, PassportMintedEvent.OutputObject>;
    

      'PassportRevoked(string,address,bytes32,uint256)': TypedContractEvent<PassportRevokedEvent.InputTuple, PassportRevokedEvent.OutputTuple, PassportRevokedEvent.OutputObject>;
      PassportRevoked: TypedContractEvent<PassportRevokedEvent.InputTuple, PassportRevokedEvent.OutputTuple, PassportRevokedEvent.OutputObject>;
    

      'PassportTransferred(string,address,address,uint256)': TypedContractEvent<PassportTransferredEvent.InputTuple, PassportTransferredEvent.OutputTuple, PassportTransferredEvent.OutputObject>;
      PassportTransferred: TypedContractEvent<PassportTransferredEvent.InputTuple, PassportTransferredEvent.OutputTuple, PassportTransferredEvent.OutputObject>;
    

      'PassportUrlsUpdated(string,string,string)': TypedContractEvent<PassportUrlsUpdatedEvent.InputTuple, PassportUrlsUpdatedEvent.OutputTuple, PassportUrlsUpdatedEvent.OutputObject>;
      PassportUrlsUpdated: TypedContractEvent<PassportUrlsUpdatedEvent.InputTuple, PassportUrlsUpdatedEvent.OutputTuple, PassportUrlsUpdatedEvent.OutputObject>;
    

      'RegistryFrozen(address,uint256)': TypedContractEvent<RegistryFrozenEvent.InputTuple, RegistryFrozenEvent.OutputTuple, RegistryFrozenEvent.OutputObject>;
      RegistryFrozen: TypedContractEvent<RegistryFrozenEvent.InputTuple, RegistryFrozenEvent.OutputTuple, RegistryFrozenEvent.OutputObject>;
    
    };
  }