/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IODPWalletLookup } from './IODPWalletLookup.js';
export type { ODPWalletDocumentAnchor } from './ODPWalletDocumentAnchor.js';