/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IODPRegistryForRelations {
      
    export type CreatorRecordStruct = {creatorId: string, wallet: AddressLike, typePrefix: BytesLike, timestamp: BigNumberish}

    export type CreatorRecordStructOutput = [creatorId: string, wallet: string, typePrefix: string, timestamp: bigint] & {creatorId: string, wallet: string, typePrefix: string, timestamp: bigint }
  
    }

  export interface IODPRegistryForRelationsInterface extends Interface {
    getFunction(nameOrSignature: "getCreator" | "getCreatorByWallet"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getCreator', values: [string]): string;
encodeFunctionData(functionFragment: 'getCreatorByWallet', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCreatorByWallet', data: BytesLike): Result;
  }

  

  export interface IODPRegistryForRelations extends BaseContract {
    
    connect(runner?: ContractRunner | null): IODPRegistryForRelations;
    waitForDeployment(): Promise<this>;

    interface: IODPRegistryForRelationsInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getCreator: TypedContractMethod<
      [creatorId: string, ],
      [IODPRegistryForRelations.CreatorRecordStructOutput],
      'view'
    >
    

    
    getCreatorByWallet: TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getCreator'): TypedContractMethod<
      [creatorId: string, ],
      [IODPRegistryForRelations.CreatorRecordStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCreatorByWallet'): TypedContractMethod<
      [wallet: AddressLike, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }