/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
    export type PassportCoreMintInputsStruct = {year: BigNumberish, month: BigNumberish, title: string, authorName: string, shortDescription: string, domain: string, contentClass: BigNumberish, lifecycleStatus: BigNumberish, aiStatus: BigNumberish, verificationMethod: BigNumberish, editionModel: BigNumberish}

    export type PassportCoreMintInputsStructOutput = [year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint] & {year: bigint, month: bigint, title: string, authorName: string, shortDescription: string, domain: string, contentClass: bigint, lifecycleStatus: bigint, aiStatus: bigint, verificationMethod: bigint, editionModel: bigint }
  

    export type PassportMintInputsStruct = {core: PassportCoreMintInputsStruct, dataHash: BytesLike, dataUrl: string, imageHash: BytesLike, imageUrl: string, fileHash: BytesLike, anchorsHash: BytesLike, anchorTypesMask: BigNumberish}

    export type PassportMintInputsStructOutput = [core: PassportCoreMintInputsStructOutput, dataHash: string, dataUrl: string, imageHash: string, imageUrl: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint] & {core: PassportCoreMintInputsStructOutput, dataHash: string, dataUrl: string, imageHash: string, imageUrl: string, fileHash: string, anchorsHash: string, anchorTypesMask: bigint }
  

  export interface ODPPassportLibInterface extends Interface {
    getFunction(nameOrSignature: "buildCreatorId" | "decodeAndValidateDigitalExtensionNorm" | "decodeAndValidatePhysicalExtensionNorm" | "decodeMintNorm" | "formatOdpPassportId" | "formatPrfId" | "monthToString" | "pad3" | "pad8" | "pad9" | "requireAnchorBits" | "resolveMintDataUrlMemory" | "stripTrailingSlashMemory" | "utcYearMonthFromTimestamp" | "validateAiStatus" | "validateCommonMintInputs" | "validateContentClass" | "validateDigitalMintInputs" | "validateEditionModel" | "validateLifecycleStatus" | "validateMixedMintInputs" | "validatePassportCore" | "validatePassportEventInputs" | "validatePhysicalMintInputs" | "validateVerificationMethod" | "yearToString"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'buildCreatorId', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'decodeAndValidateDigitalExtensionNorm', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'decodeAndValidatePhysicalExtensionNorm', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'decodeMintNorm', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'formatOdpPassportId', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'formatPrfId', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'monthToString', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pad3', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pad8', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pad9', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'requireAnchorBits', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveMintDataUrlMemory', values: [string, boolean, string]): string;
encodeFunctionData(functionFragment: 'stripTrailingSlashMemory', values: [string]): string;
encodeFunctionData(functionFragment: 'utcYearMonthFromTimestamp', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validateAiStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validateCommonMintInputs', values: [PassportMintInputsStruct]): string;
encodeFunctionData(functionFragment: 'validateContentClass', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validateDigitalMintInputs', values: [PassportMintInputsStruct]): string;
encodeFunctionData(functionFragment: 'validateEditionModel', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validateLifecycleStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'validateMixedMintInputs', values: [PassportMintInputsStruct]): string;
encodeFunctionData(functionFragment: 'validatePassportCore', values: [PassportCoreMintInputsStruct]): string;
encodeFunctionData(functionFragment: 'validatePassportEventInputs', values: [BigNumberish, BigNumberish, string, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'validatePhysicalMintInputs', values: [PassportMintInputsStruct]): string;
encodeFunctionData(functionFragment: 'validateVerificationMethod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'yearToString', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'buildCreatorId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decodeAndValidateDigitalExtensionNorm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decodeAndValidatePhysicalExtensionNorm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decodeMintNorm', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'formatOdpPassportId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'formatPrfId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'monthToString', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pad3', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pad8', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pad9', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requireAnchorBits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMintDataUrlMemory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stripTrailingSlashMemory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'utcYearMonthFromTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateAiStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateCommonMintInputs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateContentClass', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateDigitalMintInputs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateEditionModel', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateLifecycleStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateMixedMintInputs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatePassportCore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatePassportEventInputs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validatePhysicalMintInputs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'validateVerificationMethod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yearToString', data: BytesLike): Result;
  }

  

  export interface ODPPassportLib extends BaseContract {
    
    connect(runner?: ContractRunner | null): ODPPassportLib;
    waitForDeployment(): Promise<this>;

    interface: ODPPassportLibInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buildCreatorId: TypedContractMethod<
      [typePrefix: BytesLike, number: BigNumberish, ],
      [string],
      'view'
    >
    

    
    decodeAndValidateDigitalExtensionNorm: TypedContractMethod<
      [norm: BytesLike, ],
      [PassportMintInputsStructOutput],
      'view'
    >
    

    
    decodeAndValidatePhysicalExtensionNorm: TypedContractMethod<
      [norm: BytesLike, ],
      [PassportMintInputsStructOutput],
      'view'
    >
    

    
    decodeMintNorm: TypedContractMethod<
      [norm: BytesLike, ],
      [PassportMintInputsStructOutput],
      'view'
    >
    

    
    formatOdpPassportId: TypedContractMethod<
      [year: BigNumberish, month: BigNumberish, n: BigNumberish, ],
      [string],
      'view'
    >
    

    
    formatPrfId: TypedContractMethod<
      [year: BigNumberish, month: BigNumberish, n: BigNumberish, ],
      [string],
      'view'
    >
    

    
    monthToString: TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pad3: TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pad8: TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >
    

    
    pad9: TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >
    

    
    requireAnchorBits: TypedContractMethod<
      [mask: BigNumberish, required: BigNumberish, ],
      [void],
      'view'
    >
    

    
    resolveMintDataUrlMemory: TypedContractMethod<
      [dataUrl: string, dataUrlIsFolderBase: boolean, passportId: string, ],
      [string],
      'view'
    >
    

    
    stripTrailingSlashMemory: TypedContractMethod<
      [s: string, ],
      [string],
      'view'
    >
    

    
    utcYearMonthFromTimestamp: TypedContractMethod<
      [ts: BigNumberish, ],
      [[bigint, bigint] & {year: bigint, month: bigint }],
      'view'
    >
    

    
    validateAiStatus: TypedContractMethod<
      [aiStatus: BigNumberish, ],
      [void],
      'view'
    >
    

    
    validateCommonMintInputs: TypedContractMethod<
      [m: PassportMintInputsStruct, ],
      [void],
      'view'
    >
    

    
    validateContentClass: TypedContractMethod<
      [contentClass: BigNumberish, ],
      [void],
      'view'
    >
    

    
    validateDigitalMintInputs: TypedContractMethod<
      [m: PassportMintInputsStruct, ],
      [void],
      'view'
    >
    

    
    validateEditionModel: TypedContractMethod<
      [editionModel: BigNumberish, ],
      [void],
      'view'
    >
    

    
    validateLifecycleStatus: TypedContractMethod<
      [lifecycleStatus: BigNumberish, ],
      [void],
      'view'
    >
    

    
    validateMixedMintInputs: TypedContractMethod<
      [m: PassportMintInputsStruct, ],
      [void],
      'view'
    >
    

    
    validatePassportCore: TypedContractMethod<
      [core: PassportCoreMintInputsStruct, ],
      [void],
      'view'
    >
    

    
    validatePassportEventInputs: TypedContractMethod<
      [kind: BigNumberish, value: BigNumberish, note: string, attachmentHash: BytesLike, attachmentUrl: string, ],
      [void],
      'view'
    >
    

    
    validatePhysicalMintInputs: TypedContractMethod<
      [m: PassportMintInputsStruct, ],
      [void],
      'view'
    >
    

    
    validateVerificationMethod: TypedContractMethod<
      [verificationMethod: BigNumberish, ],
      [void],
      'view'
    >
    

    
    yearToString: TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buildCreatorId'): TypedContractMethod<
      [typePrefix: BytesLike, number: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'decodeAndValidateDigitalExtensionNorm'): TypedContractMethod<
      [norm: BytesLike, ],
      [PassportMintInputsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'decodeAndValidatePhysicalExtensionNorm'): TypedContractMethod<
      [norm: BytesLike, ],
      [PassportMintInputsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'decodeMintNorm'): TypedContractMethod<
      [norm: BytesLike, ],
      [PassportMintInputsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'formatOdpPassportId'): TypedContractMethod<
      [year: BigNumberish, month: BigNumberish, n: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'formatPrfId'): TypedContractMethod<
      [year: BigNumberish, month: BigNumberish, n: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'monthToString'): TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pad3'): TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pad8'): TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pad9'): TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requireAnchorBits'): TypedContractMethod<
      [mask: BigNumberish, required: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'resolveMintDataUrlMemory'): TypedContractMethod<
      [dataUrl: string, dataUrlIsFolderBase: boolean, passportId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stripTrailingSlashMemory'): TypedContractMethod<
      [s: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'utcYearMonthFromTimestamp'): TypedContractMethod<
      [ts: BigNumberish, ],
      [[bigint, bigint] & {year: bigint, month: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'validateAiStatus'): TypedContractMethod<
      [aiStatus: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validateCommonMintInputs'): TypedContractMethod<
      [m: PassportMintInputsStruct, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validateContentClass'): TypedContractMethod<
      [contentClass: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validateDigitalMintInputs'): TypedContractMethod<
      [m: PassportMintInputsStruct, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validateEditionModel'): TypedContractMethod<
      [editionModel: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validateLifecycleStatus'): TypedContractMethod<
      [lifecycleStatus: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validateMixedMintInputs'): TypedContractMethod<
      [m: PassportMintInputsStruct, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validatePassportCore'): TypedContractMethod<
      [core: PassportCoreMintInputsStruct, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validatePassportEventInputs'): TypedContractMethod<
      [kind: BigNumberish, value: BigNumberish, note: string, attachmentHash: BytesLike, attachmentUrl: string, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validatePhysicalMintInputs'): TypedContractMethod<
      [m: PassportMintInputsStruct, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'validateVerificationMethod'): TypedContractMethod<
      [verificationMethod: BigNumberish, ],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'yearToString'): TypedContractMethod<
      [v: BigNumberish, ],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }